# Generated from ../test_linalg.sage by Sage's preparser (run_cpython.py --regen).
_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_12 = Integer(12); _sage_const_14 = Integer(14); _sage_const_30 = Integer(30); _sage_const_1009 = Integer(1009); _sage_const_504 = Integer(504); _sage_const_29 = Integer(29); _sage_const_23 = Integer(23); _sage_const_300 = Integer(300); _sage_const_19 = Integer(19); _sage_const_250 = Integer(250); _sage_const_120 = Integer(120); _sage_const_100 = Integer(100); _sage_const_400 = Integer(400)# Exact linear algebra over ZZ and QQ (sagebrush.linalg) and long
# polynomial products and gcds (sagebrush.poly), against Sage.
A = matrix(QQ, [[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_4 ,_sage_const_5 ,_sage_const_6 ],[_sage_const_7 ,_sage_const_8 ,_sage_const_10 ]])
print(A.det())
print(A.rank())
print(A.inverse())
print(A.charpoly())
print(A.charpoly('t'))
print(~A * A == identity_matrix(QQ, _sage_const_3 ))
B = matrix(QQ, [[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_4 ,_sage_const_5 ,_sage_const_6 ],[_sage_const_7 ,_sage_const_8 ,_sage_const_9 ]])
print(B.det(), B.rank(), B.pivots())
print(B.echelon_form())
print(B.kernel())
print(B.right_kernel())
print(B.solve_right(vector([_sage_const_1 ,_sage_const_2 ,_sage_const_3 ])))
print(B.solve_left(vector([_sage_const_1 ,_sage_const_2 ,_sage_const_3 ])))
try:
    B.solve_right(vector([_sage_const_1 ,_sage_const_0 ,_sage_const_0 ]))
except ValueError as e:
    print("ValueError:", e)
try:
    B.inverse()
except ZeroDivisionError as e:
    print("ZeroDivisionError:", e)
C = matrix(QQ, [[_sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_3 , _sage_const_1 /_sage_const_5 ], [_sage_const_2 /_sage_const_7 , _sage_const_3 /_sage_const_11 , _sage_const_5 /_sage_const_13 ], [_sage_const_1 , -_sage_const_1 , _sage_const_1 /_sage_const_17 ]])
print(C.det())
print(C.inverse())
print(C.charpoly())
print(C.solve_right(vector([_sage_const_1 , _sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_3 ])))
print(C.solve_right(matrix(QQ, [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ], [_sage_const_1 , _sage_const_1 ]])))
Z = matrix(ZZ, [[_sage_const_2 ,_sage_const_4 ,_sage_const_6 ],[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ]])
print(Z.kernel())
print(Z.right_kernel())
print(Z.rank(), Z.det() if Z.is_square() else "not square")
D = matrix(ZZ, _sage_const_12 , _sage_const_12 , [power_mod(i + _sage_const_2 , j + _sage_const_3 , _sage_const_17 ) - _sage_const_8  for i in range(_sage_const_12 ) for j in range(_sage_const_12 )])
print(D.det())
print(D.charpoly())
print(D.rank())
E = matrix(ZZ, _sage_const_10 , _sage_const_14 , [power_mod(i % _sage_const_5  + _sage_const_2 , j + _sage_const_1 , _sage_const_11 ) - _sage_const_5  for i in range(_sage_const_10 ) for j in range(_sage_const_14 )])
print(E.rank(), E.pivots())
print(E.right_kernel())
print(E.echelon_form() == E.hermite_form())
print(E.change_ring(QQ).echelon_form())
F = matrix(ZZ, _sage_const_30 , _sage_const_30 , [power_mod(i + _sage_const_2 , j + _sage_const_3 , _sage_const_1009 ) - _sage_const_504  for i in range(_sage_const_30 ) for j in range(_sage_const_30 )])
print(F.det())
print(F.inverse()[_sage_const_0 ][_sage_const_0 ], F.inverse()[_sage_const_29 ][_sage_const_29 ])
x = vector(QQ, [_sage_const_1 ]*_sage_const_30 )
s = F.solve_right(x)
print(F * s == x)
print(s[_sage_const_0 ])
print(matrix(ZZ,[[_sage_const_1 ,_sage_const_2 ],[_sage_const_3 ,_sage_const_4 ]]) * vector([_sage_const_1 ,_sage_const_1 ]))
print(matrix(ZZ, _sage_const_0 , _sage_const_3 ).kernel())
print(matrix(QQ, [[_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ]]).kernel())
# long products and gcds of polynomials
R = ZZ['x']; (x,) = R._first_ngens(1)
f = sum(((i*i + _sage_const_1 ) % _sage_const_23  - _sage_const_11 ) * x**i for i in range(_sage_const_300 ))
g = sum(((i*_sage_const_7  + _sage_const_2 ) % _sage_const_19  - _sage_const_9 ) * x**i for i in range(_sage_const_250 ))
h = sum(((i*_sage_const_5  + _sage_const_3 ) % _sage_const_13  - _sage_const_6 ) * x**i for i in range(_sage_const_120 ))
print((f*g).degree(), (f*g)[_sage_const_100 ], (f*g)[_sage_const_400 ], (f*g).coefficients()[:_sage_const_5 ])
print((f*h).gcd(g*h) == h * (f.gcd(g)) or (f*h).gcd(g*h) == -h * (f.gcd(g)))
print(((f*h).gcd(g*h)).degree(), ((f*h).gcd(g*h)).leading_coefficient())
print((_sage_const_2 *x+_sage_const_2 ).gcd(_sage_const_4 *x+_sage_const_4 ), (_sage_const_6 *x**_sage_const_2 -_sage_const_6 ).gcd(_sage_const_4 *x-_sage_const_4 ), R(_sage_const_0 ).gcd(R(-_sage_const_3 )), (-x).gcd(R(_sage_const_0 )))
S = QQ['y']; (y,) = S._first_ngens(1)
p = S(f) / _sage_const_3 
q = S(g) * (_sage_const_2 /_sage_const_5 )
print((p*S(h)).gcd(q*S(h)) == S(h).monic() * S(f).gcd(S(g)))
print((y**_sage_const_2  - _sage_const_1 ).gcd(y**_sage_const_2  + _sage_const_2 *y + _sage_const_1 ))