// Number fields, class and unit groups, integer matrices, factoring:
// the Rust engine (engine/classgroup). Class groups assume GRH.
P<x> := PolynomialRing(Integers());
K<a> := NumberField(x^3 - 11);
K;
Discriminant(K);
Degree(K);
Signature(K);
O := MaximalOrder(K);
O;
Discriminant(O);
ClassNumber(K);
IntegralBasis(K);
Factorization(2^128+1);
M := Matrix(Integers(), [[4,6,2],[3,9,12],[1,1,1]]);
M;
HermiteForm(M);
ElementaryDivisors(M);
LLL(Matrix(Integers(), [[1,2,3],[4,5,6],[7,8,10]]));
L<b> := NumberField(x^3 + x^2 - 2*x + 8);
IntegralBasis(L);
Q<s> := QuadraticField(-23);
ClassNumber(Q);
(a+1)^3;
Norm(a+1);
Trace(a+1);
MinimalPolynomial(a+1);
Q<s> := QuadraticField(-23);
Q;
Q2 := QuadraticField(10);
Q2;
L<b> := NumberField(x^3 + x^2 - 2*x + 8);
MaximalOrder(L);
IntegralBasis(L);
K<a> := NumberField(x^3 - 2);
U := UnitGroup(MaximalOrder(K));
U;
C, m := ClassGroup(NumberField(x^3-11));
C;
UnitGroup(NumberField(x^2+3));
M := Matrix(Integers(), 2, 3, [2,-4,6,3,0,-1]);
M;
HermiteForm(M);
Rank(M);
ElementaryDivisors(M);
Determinant(Matrix(Integers(), [[1,2],[3,4]]));
Transpose(M);
NumberOfRows(M), NumberOfColumns(M);
M[1];
M[2][3];
1/2*b;
(b^2+b)/2;
a^-1;
Signature(NumberField(x^4 - 10*x^2 + 1));
