M := ModularSymbols(11, 2);
M;
M := ModularSymbols(11, 2, 1);
M;
Dimension(M);
CharacteristicPolynomial(HeckeOperator(M, 2));
HeckePolynomial(CuspidalSubspace(ModularSymbols(389,2,1)), 2);
Factorization(HeckePolynomial(ModularSymbols(11,2,1),2));
P := HeckePolynomial(ModularSymbols(23,2,1), 2); P; Parent(P);
M := ModularSymbols(37, 2); Dimension(CuspidalSubspace(M)), Dimension(NewSubspace(CuspidalSubspace(M)));
M := ModularSymbols(Gamma0(37), 2, 1); M;
M := ModularSymbols(33, 4, 1); Dimension(M); NewSubspace(CuspidalSubspace(M));
S := CuspidalSubspace(ModularSymbols(389, 2, 1)); S;
Factorization(HeckePolynomial(S, 2));
NewformDecomposition(NewSubspace(S));
C := CuspForms(11, 2); C;
Dimension(CuspForms(389, 2));
N := Newforms(CuspForms(37, 2)); N; #N;
f := N[1][1]; f; Parent(f);
qExpansion(f, 10);
N := Newforms(CuspForms(11, 2)); N;
qExpansion(N[1][1], 6);
DimensionNewCuspFormsGamma0(389, 2), DimensionCuspFormsGamma0(389, 2);
E := EllipticCurve([0, -1, 1, -10, -20]); E;
TraceOfFrobenius(E, 7), Conductor(E), aInvariants(E);
[TraceOfFrobenius(E, p) : p in PrimesUpTo(30)];
Discriminant(E);
TorsionSubgroup(E);
E2 := EllipticCurve("389a1"); E2; Rank(E2);
TorsionSubgroup(EllipticCurve([1,0,1,-19,26]));
TorsionSubgroup(EllipticCurve("37a1"));
#TorsionSubgroup(EllipticCurve("15a1"));
TorsionSubgroup(EllipticCurve("15a1"));
E := EllipticCurve("11a3"); E; jInvariant(E); Discriminant(E);
EllipticCurve([1,2]);
E := EllipticCurve([0,0,0,-1,0]); Conductor(E); E;
CremonaReference(EllipticCurve([0, -1, 1, -10, -20]));
