//! Galois orbits of newforms at prime level N <= 300 against Sage: the
//! dimension of every orbit and tr(T_p | A) for primes p <= 200, p != N
//! (fixtures/sage_prime_orbits_le300.jsonl, generated by
//! `sage fixtures/make_sage_prime_orbits.sage 11 300 OUT`).  Factoring
//! is sagebrush-poly's.

use std::collections::HashMap;

#[test]
fn prime_level_orbits_match_sage_up_to_300() {
    let mut sage: HashMap<u64, Vec<(usize, Vec<(u64, i64)>)>> = HashMap::new();
    for line in include_str!("fixtures/sage_prime_orbits_le300.jsonl").lines() {
        let v: serde_json::Value = serde_json::from_str(line).unwrap();
        let mut tr: Vec<(u64, i64)> = v["traces"].as_object().unwrap().iter().map(|(p, t)| (p.parse().unwrap(), t.as_i64().unwrap())).collect();
        tr.sort();
        sage.entry(v["level"].as_u64().unwrap()).or_default().push((v["dim"].as_u64().unwrap() as usize, tr));
    }
    let factor = |f: &[sagebrush_bigint::BigInt]| sagebrush_poly::factor(f).1;
    let mut count = 0;
    for (&n, theirs) in sage.iter_mut() {
        let orbits = sagebrush_modsym::orbits::prime_level_orbits(n, 200, &factor).unwrap();
        let mut ours: Vec<(usize, Vec<(u64, i64)>)> = orbits.into_iter().map(|o| (o.dim, o.traces)).collect();
        ours.sort();
        theirs.sort();
        assert_eq!(&ours, theirs, "N={}", n);
        count += ours.len();
    }
    assert_eq!(count, include_str!("fixtures/sage_prime_orbits_le300.jsonl").lines().count());
}

/// Every level N <= 200, composite ones included (oldforms, Eisenstein
/// series with characters): orbit dimensions and tr(T_p | A) for primes
/// p <= 100 not dividing N, against Sage (fixtures/sage_orbits_le200.jsonl,
/// from `sage fixtures/make_sage_orbits.sage 1 200 OUT`).
#[test]
fn newform_orbits_match_sage_up_to_200() {
    let mut sage: HashMap<u64, Vec<(usize, Vec<(u64, i64)>)>> = HashMap::new();
    for line in include_str!("fixtures/sage_orbits_le200.jsonl").lines() {
        let v: serde_json::Value = serde_json::from_str(line).unwrap();
        let mut tr: Vec<(u64, i64)> = v["traces"].as_object().unwrap().iter().map(|(p, t)| (p.parse().unwrap(), t.as_i64().unwrap())).collect();
        tr.sort();
        sage.entry(v["level"].as_u64().unwrap()).or_default().push((v["dim"].as_u64().unwrap() as usize, tr));
    }
    let factor = |f: &[sagebrush_bigint::BigInt]| sagebrush_poly::factor(f).1;
    let mut count = 0;
    for n in 1..=200u64 {
        let orbits = sagebrush_modsym::orbits::newform_orbits(n, 100, &factor).unwrap();
        let mut ours: Vec<(usize, Vec<(u64, i64)>)> = orbits.into_iter().map(|o| (o.dim, o.traces)).collect();
        let mut theirs = sage.remove(&n).unwrap_or_default();
        ours.sort();
        theirs.sort();
        assert_eq!(ours, theirs, "N={}", n);
        count += ours.len();
    }
    assert_eq!(count, include_str!("fixtures/sage_orbits_le200.jsonl").lines().count());
}

#[test]
fn new_dimension_formula() {
    use sagebrush_modsym::orbits::new_dimension;
    // dim S_2^new: 11 -> 1, 22 -> 0 (old only), 23 -> 2, 37 -> 2, 389 -> 32, 960 -> 16 + non-rational
    assert_eq!(new_dimension(11), 1);
    assert_eq!(new_dimension(22), 0);
    assert_eq!(new_dimension(23), 2);
    assert_eq!(new_dimension(37), 2);
    assert_eq!(new_dimension(389), 32);
}

/// A factor callback may return factors with leading coefficient -1 (in
/// pairs, so the product is still f): they are made monic before the monic
/// divisions (R2-MOD-F3: a_2 = 788130959 at level 11).
#[test]
fn negative_leading_factors_are_normalised() {
    use sagebrush_bigint::BigInt;
    let factor = |f: &[BigInt]| {
        let mut fs = sagebrush_poly::factor(f).1;
        let mut flipped = 0;
        for (g, e) in fs.iter_mut() {
            if *e == 1 && flipped < 2 {
                for c in g.iter_mut() {
                    *c = -c.clone();
                }
                flipped += 1;
            }
        }
        if flipped == 1 {
            let (g, _) = fs.iter_mut().find(|(g, _)| g.last().unwrap() < &BigInt::from(0)).unwrap();
            for c in g.iter_mut() {
                *c = -c.clone();
            }
        }
        fs
    };
    for (n, want) in [(11u64, vec![(2u64, -2i64), (3, -1), (5, 1), (7, -2)]), (23, vec![(2, -1), (3, 0), (5, -2), (7, 2)])] {
        let orbits = sagebrush_modsym::orbits::newform_orbits(n, 7, &factor).unwrap();
        let traces: Vec<Vec<(u64, i64)>> = orbits.into_iter().map(|o| o.traces).collect();
        assert!(traces.contains(&want), "N={}: {:?}", n, traces);
    }
}
