//! Permutation groups: a generating set and a (proven) stabilizer chain, and
//! the basic algorithms on them.

use crate::chain::Chain;
use crate::perm::{Perm, Rng};
use sagebrush_bigint::BigInt;
use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug)]
pub struct Group {
    pub n: usize,
    pub gens: Vec<Perm>,
    pub chain: Chain,
}

impl Group {
    /// The group generated by `gens` on {0..n-1}.
    pub fn new(n: usize, gens: Vec<Perm>) -> Result<Group, String> {
        Group::with_base(n, gens, &[])
    }

    /// The same, with a base starting with `prefix`.
    pub fn with_base(n: usize, gens: Vec<Perm>, prefix: &[u32]) -> Result<Group, String> {
        if let Some(g) = gens.iter().find(|g| g.degree() != n) {
            return Err(format!("a generator has degree {}, not {}", g.degree(), n));
        }
        if let Some(&b) = prefix.iter().find(|&&b| b as usize >= n) {
            return Err(format!("point {} is outside 0..{}", b, n));
        }
        let chain = Chain::new(n, &gens, prefix);
        Ok(Group { n, gens, chain })
    }

    pub fn trivial(n: usize) -> Group {
        Group { n, gens: vec![], chain: Chain { n, levels: vec![] } }
    }

    pub fn order(&self) -> BigInt {
        self.chain.order()
    }

    pub fn contains(&self, g: &Perm) -> bool {
        g.degree() == self.n && self.chain.contains(g)
    }

    /// Is every generator of h in self?
    pub fn contains_group(&self, h: &Group) -> bool {
        h.gens.iter().all(|g| self.contains(g))
    }

    pub fn is_trivial(&self) -> bool {
        self.gens.iter().all(|g| g.is_identity())
    }

    pub fn orbit(&self, x: u32) -> Vec<u32> {
        let mut seen = vec![false; self.n];
        seen[x as usize] = true;
        let mut orb = vec![x];
        let mut i = 0;
        while i < orb.len() {
            for g in &self.gens {
                let y = g.image(orb[i]);
                if !seen[y as usize] {
                    seen[y as usize] = true;
                    orb.push(y);
                }
            }
            i += 1;
        }
        orb.sort_unstable();
        orb
    }

    /// All orbits on {0..n-1} (fixed points included), by smallest point.
    pub fn orbits(&self) -> Vec<Vec<u32>> {
        let mut seen = vec![false; self.n];
        let mut out = vec![];
        for x in 0..self.n as u32 {
            if !seen[x as usize] {
                let o = self.orbit(x);
                for &y in &o {
                    seen[y as usize] = true;
                }
                out.push(o);
            }
        }
        out
    }

    pub fn is_transitive(&self) -> bool {
        self.n <= 1 || self.orbit(0).len() == self.n
    }

    /// The stabilizer of x.
    pub fn stabilizer(&self, x: u32) -> Group {
        let full = if self.chain.levels.first().map(|l| l.base) == Some(x) {
            self.clone()
        } else {
            Group::with_base(self.n, self.gens.clone(), &[x]).unwrap()
        };
        let tail = full.chain.tail();
        let gens = tail.strong_gens();
        Group { n: self.n, gens, chain: tail }
    }

    /// The pointwise stabilizer of a sequence of points.
    pub fn pointwise_stabilizer(&self, pts: &[u32]) -> Group {
        let mut full = Group::with_base(self.n, self.gens.clone(), pts).unwrap();
        for _ in 0..pts.len() {
            full.chain = full.chain.tail();
        }
        full.gens = full.chain.strong_gens();
        full
    }

    pub fn random(&self, rng: &mut Rng) -> Perm {
        self.chain.random(rng)
    }

    /// The elements, if there are at most `limit`.
    pub fn elements(&self, limit: u64) -> Option<Vec<Perm>> {
        if self.order() > BigInt::from(limit) {
            return None;
        }
        Some(self.chain.elements())
    }

    // ---------------------------------------------------------------- blocks

    /// The smallest block (for the action on the points) containing `seed`:
    /// the class of seed[0] in the finest G-invariant equivalence relation
    /// identifying the points of seed (Atkinson's algorithm, with union-find).
    /// For a transitive group this is a block of imprimitivity.
    pub fn min_block(&self, seed: &[u32]) -> Vec<u32> {
        let n = self.n;
        let mut parent: Vec<u32> = (0..n as u32).collect();
        fn find(p: &mut [u32], mut x: u32) -> u32 {
            while p[x as usize] != x {
                p[x as usize] = p[p[x as usize] as usize];
                x = p[x as usize];
            }
            x
        }
        let mut queue: Vec<(u32, u32)> = vec![];
        for &y in &seed[1..] {
            let (a, b) = (find(&mut parent, seed[0]), find(&mut parent, y));
            if a != b {
                parent[b as usize] = a;
                queue.push((seed[0], y));
            }
        }
        while let Some((x, y)) = queue.pop() {
            for g in &self.gens {
                let (u, v) = (g.image(x), g.image(y));
                let (a, b) = (find(&mut parent, u), find(&mut parent, v));
                if a != b {
                    parent[b as usize] = a;
                    queue.push((u, v));
                }
            }
        }
        let r = find(&mut parent, seed[0]);
        let mut out: Vec<u32> = (0..n as u32).filter(|&x| find(&mut parent, x) == r).collect();
        out.sort_unstable();
        out
    }

    /// For a transitive group: every nontrivial block containing x (one for
    /// each nontrivial block system), smallest first.
    pub fn blocks_containing(&self, x: u32) -> Vec<Vec<u32>> {
        let n = self.n;
        // the blocks generated by x and one more point; y and y^h (h fixing x)
        // give the same block, so one y from each orbit of the stabilizer
        let stab = self.stabilizer(x);
        let mut atoms: BTreeSet<Vec<u32>> = BTreeSet::new();
        for o in stab.orbits() {
            if o[0] == x {
                continue;
            }
            let b = self.min_block(&[x, o[0]]);
            if b.len() < n {
                atoms.insert(b);
            }
        }
        // every block containing x is a join of these
        let mut found = atoms.clone();
        let mut queue: Vec<Vec<u32>> = atoms.iter().cloned().collect();
        while let Some(b) = queue.pop() {
            sagebrush_interrupt::check();
            for a in &atoms {
                if a.iter().all(|p| b.binary_search(p).is_ok()) {
                    continue;
                }
                let mut seed = b.clone();
                seed.extend(a.iter().filter(|p| b.binary_search(p).is_err()));
                let c = self.min_block(&seed);
                if c.len() < n && found.insert(c.clone()) {
                    queue.push(c);
                }
            }
        }
        let mut out: Vec<Vec<u32>> = found.into_iter().collect();
        out.sort_by(|a, b| a.len().cmp(&b.len()).then(a.cmp(b)));
        out
    }

    /// The block system containing the block b: the images of b.
    pub fn block_system(&self, b: &[u32]) -> Vec<Vec<u32>> {
        let mut sys: BTreeSet<Vec<u32>> = BTreeSet::new();
        sys.insert(b.to_vec());
        let mut queue = vec![b.to_vec()];
        while let Some(c) = queue.pop() {
            for g in &self.gens {
                let mut d: Vec<u32> = c.iter().map(|&p| g.image(p)).collect();
                d.sort_unstable();
                if sys.insert(d.clone()) {
                    queue.push(d);
                }
            }
        }
        sys.into_iter().collect()
    }

    pub fn is_primitive(&self) -> bool {
        if !self.is_transitive() {
            return false;
        }
        if self.n <= 2 {
            return true;
        }
        let stab = self.stabilizer(0);
        stab.orbits().iter().filter(|o| o[0] != 0).all(|o| self.min_block(&[0, o[0]]).len() == self.n)
    }

    /// The largest k such that the group is k-transitive on {0..n-1}.
    pub fn transitivity(&self) -> usize {
        let mut k = 0;
        let mut g = self.clone();
        let mut fixed: Vec<u32> = vec![];
        loop {
            // is g transitive on the points not yet fixed?
            let rest: Vec<u32> = (0..self.n as u32).filter(|p| !fixed.contains(p)).collect();
            if rest.is_empty() {
                return k;
            }
            if g.orbit(rest[0]).len() != rest.len() {
                return k;
            }
            k += 1;
            fixed.push(rest[0]);
            g = g.stabilizer(rest[0]);
        }
    }

    // ---------------------------------------------------------------- subgroups

    /// The subgroup generated by `gens` (inside the same symmetric group).
    pub fn subgroup(&self, gens: Vec<Perm>) -> Group {
        Group::new(self.n, gens).unwrap()
    }

    /// The normal closure in self of the subgroup generated by `gens`.
    pub fn normal_closure(&self, gens: &[Perm]) -> Group {
        let mut ngens: Vec<Perm> = gens.iter().filter(|g| !g.is_identity()).cloned().collect();
        let mut nn = Group::new(self.n, ngens.clone()).unwrap();
        let mut i = 0;
        while i < ngens.len() {
            for g in &self.gens {
                sagebrush_interrupt::check();
                let c = ngens[i].conj(g);
                if !nn.contains(&c) {
                    ngens.push(c);
                    // rebuild from the strong generators found so far
                    let mut sg = nn.chain.strong_gens();
                    sg.push(ngens.last().unwrap().clone());
                    nn = Group { n: self.n, gens: vec![], chain: Chain::new(self.n, &sg, &[]) };
                }
            }
            i += 1;
        }
        nn.gens = ngens;
        nn.reduce_gens();
        nn
    }

    /// Replace a long generating list by a few random elements generating the
    /// same group (checked against the order, so the result is exact).
    pub fn reduce_gens(&mut self) {
        if self.gens.len() <= 4 {
            return;
        }
        let target = self.order();
        let mut rng = Rng::new(0x9e37 ^ self.gens.len() as u64);
        let mut gs: Vec<Perm> = vec![];
        let mut sub = Group::trivial(self.n);
        for _ in 0..64 {
            sagebrush_interrupt::check();
            let r = self.random(&mut rng);
            if sub.contains(&r) {
                continue;
            }
            gs.push(r);
            sub = Group::new(self.n, gs.clone()).unwrap();
            if sub.order() == target {
                self.gens = gs;
                return;
            }
        }
        // (not reached in practice: keep the long list)
    }

    /// [G, G]
    pub fn derived_subgroup(&self) -> Group {
        let mut cs = vec![];
        for (i, a) in self.gens.iter().enumerate() {
            for b in &self.gens[i + 1..] {
                let c = a.comm(b);
                if !c.is_identity() {
                    cs.push(c);
                }
            }
        }
        self.normal_closure(&cs)
    }

    /// G = G_0 > G_1 = [G, G] > ... until it stops shrinking.
    pub fn derived_series(&self) -> Vec<Group> {
        let mut out = vec![self.clone()];
        loop {
            let d = out.last().unwrap().derived_subgroup();
            if d.order() == out.last().unwrap().order() {
                return out;
            }
            let trivial = d.is_trivial();
            out.push(d);
            if trivial {
                return out;
            }
        }
    }

    pub fn is_abelian(&self) -> bool {
        self.gens.iter().enumerate().all(|(i, a)| self.gens[i + 1..].iter().all(|b| a.mul(b) == b.mul(a)))
    }

    pub fn is_solvable(&self) -> bool {
        self.derived_series().last().unwrap().is_trivial()
    }

    /// Is h (a subgroup of self) normal in self?
    pub fn is_normal(&self, h: &Group) -> bool {
        h.gens.iter().all(|a| self.gens.iter().all(|g| h.contains(&a.conj(g))))
    }

    /// The number of elements of each cycle type: exact (by listing the
    /// elements) when the order is at most `limit`, else from `samples`
    /// uniformly random elements, scaled to the order.
    pub fn cycle_type_counts(&self, limit: u64, samples: usize, rng: &mut Rng) -> (BTreeMap<Vec<usize>, u64>, bool) {
        let mut counts: BTreeMap<Vec<usize>, u64> = BTreeMap::new();
        if let Some(els) = self.elements(limit) {
            for g in els {
                *counts.entry(g.cycle_type()).or_default() += 1;
            }
            (counts, true)
        } else {
            for _ in 0..samples {
                *counts.entry(self.random(rng).cycle_type()).or_default() += 1;
            }
            (counts, false)
        }
    }
}
