//! Conjugacy classes of subgroups of a (smallish) permutation group, by the
//! cyclic extension method (Neubueser, 1960), over an indexed table of the
//! group's elements.
//!
//! Every subgroup K has a perfect core R (the last term of its derived
//! series) and a chain R = K_0 < K_1 < ... < K_m = K with each K_i normal of
//! prime index in K_{i+1}, so K_{i+1} = <K_i, g> with g in the normalizer of
//! K_i and g^p in K_i.  Starting from the trivial group and the perfect
//! subgroups (up to conjugacy), extending each class representative H by
//! the elements g of N(H) whose coset gH has prime order reaches a
//! conjugate of every subgroup: if K_i = H^x then K_{i+1}^(x^-1) = <H,
//! g^(x^-1)>.  The perfect subgroups are found as the perfect groups
//! generated by an involution and one more element; every nonabelian
//! finite simple group is generated that way (Aschbacher and Guralnick),
//! and the counts are checked against the known numbers of subgroup classes.
//!
//! Normalizers and conjugacy tests are by brute force over the elements, so
//! this is for groups of order up to a few hundred thousand: the symmetric
//! groups of degree <= 9 and the wreath products from which transitive
//! groups of larger degree are built.

use crate::group::Group;
use crate::perm::Perm;
use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};

/// FNV-1a, fast for short keys
#[derive(Default)]
struct Fnv(u64);
impl Hasher for Fnv {
    fn finish(&self) -> u64 {
        self.0
    }
    fn write(&mut self, bytes: &[u8]) {
        let mut h = if self.0 == 0 { 0xcbf29ce484222325 } else { self.0 };
        for &b in bytes {
            h ^= b as u64;
            h = h.wrapping_mul(0x100000001b3);
        }
        self.0 = h;
    }
}
type FnvMap<K, V> = HashMap<K, V, BuildHasherDefault<Fnv>>;

/// The elements of a group, numbered, with products by table lookup.
pub struct Table {
    pub n: usize,
    pub order: usize,
    /// images, `n` bytes per element
    data: Vec<u8>,
    index: FnvMap<Box<[u8]>, u32>,
    /// the cycle type of each element, as an index into `types`
    pub ctype: Vec<u32>,
    pub types: Vec<Vec<usize>>,
}

impl Table {
    pub fn new(g: &Group, limit: usize) -> Result<Table, String> {
        if g.n > 255 {
            return Err("degree above 255".into());
        }
        let els = g.elements(limit as u64).ok_or_else(|| format!("the group has more than {} elements", limit))?;
        let n = g.n;
        let mut data = Vec::with_capacity(els.len() * n);
        let mut index: FnvMap<Box<[u8]>, u32> = FnvMap::default();
        let mut types: Vec<Vec<usize>> = vec![];
        let mut tmap: HashMap<Vec<usize>, u32> = HashMap::new();
        let mut ctype = Vec::with_capacity(els.len());
        // the identity first
        let mut els = els;
        if let Some(pos) = els.iter().position(|p| p.is_identity()) {
            els.swap(0, pos);
        }
        for (i, p) in els.iter().enumerate() {
            let b: Box<[u8]> = p.0.iter().map(|&x| x as u8).collect();
            data.extend_from_slice(&b);
            index.insert(b, i as u32);
            let t = p.cycle_type();
            let k = *tmap.entry(t.clone()).or_insert_with(|| {
                types.push(t);
                (types.len() - 1) as u32
            });
            ctype.push(k);
        }
        Ok(Table { n, order: els.len(), data, index, ctype, types })
    }

    #[inline]
    fn el(&self, i: u32) -> &[u8] {
        &self.data[i as usize * self.n..(i as usize + 1) * self.n]
    }

    pub fn perm(&self, i: u32) -> Perm {
        Perm(self.el(i).iter().map(|&x| x as u32).collect())
    }

    pub fn lookup(&self, p: &Perm) -> Option<u32> {
        let b: Vec<u8> = p.0.iter().map(|&x| x as u8).collect();
        self.index.get(&b[..]).copied()
    }

    /// a then b
    pub fn mul(&self, a: u32, b: u32) -> u32 {
        let (x, y) = (self.el(a), self.el(b));
        let mut buf = [0u8; 256];
        for k in 0..self.n {
            buf[k] = y[x[k] as usize];
        }
        self.index[&buf[..self.n]]
    }

    /// x^-1 a x
    pub fn conj(&self, a: u32, x: u32) -> u32 {
        // (x^-1 a x)(x(k)) = x(a(k))
        let (pa, px) = (self.el(a), self.el(x));
        let mut buf = [0u8; 256];
        for k in 0..self.n {
            buf[px[k] as usize] = px[pa[k] as usize];
        }
        self.index[&buf[..self.n]]
    }
}

/// A subgroup, as a set of element numbers (a bitset) with generators.
#[derive(Clone)]
pub struct Sub {
    pub bits: Vec<u64>,
    pub size: usize,
    pub gens: Vec<u32>,
}

impl Sub {
    fn trivial(order: usize) -> Sub {
        let mut bits = vec![0u64; order.div_ceil(64)];
        bits[0] |= 1;
        Sub { bits, size: 1, gens: vec![] }
    }
    #[inline]
    pub fn has(&self, i: u32) -> bool {
        self.bits[i as usize >> 6] >> (i & 63) & 1 == 1
    }
    fn set(&mut self, i: u32) -> bool {
        let w = &mut self.bits[i as usize >> 6];
        let m = 1u64 << (i & 63);
        let new = *w & m == 0;
        *w |= m;
        new
    }
    pub fn elements(&self) -> Vec<u32> {
        let mut out = Vec::with_capacity(self.size);
        for (w, &word) in self.bits.iter().enumerate() {
            let mut x = word;
            while x != 0 {
                let b = x.trailing_zeros();
                out.push((w as u32) << 6 | b);
                x &= x - 1;
            }
        }
        out
    }
}

/// An invariant of a subgroup's conjugacy class: order, orbit lengths and
/// the number of elements of each cycle type.
fn key(t: &Table, h: &Sub) -> Vec<u64> {
    let mut k = vec![h.size as u64];
    // orbits on points
    let gens: Vec<Perm> = h.gens.iter().map(|&g| t.perm(g)).collect();
    let mut seen = vec![false; t.n];
    let mut lens = vec![];
    for s in 0..t.n {
        if seen[s] {
            continue;
        }
        let mut orb = vec![s];
        seen[s] = true;
        let mut i = 0;
        while i < orb.len() {
            for g in &gens {
                let y = g.0[orb[i]] as usize;
                if !seen[y] {
                    seen[y] = true;
                    orb.push(y);
                }
            }
            i += 1;
        }
        lens.push(orb.len() as u64);
    }
    lens.sort_unstable();
    k.push(lens.len() as u64);
    k.extend(lens);
    let mut hist = vec![0u64; t.types.len()];
    for e in h.elements() {
        hist[t.ctype[e as usize] as usize] += 1;
    }
    k.extend(hist);
    // orbit lengths on unordered pairs of points
    let n = t.n;
    let pid = |a: usize, b: usize| if a < b { a * n + b } else { b * n + a };
    let mut seen = vec![false; n * n];
    let mut plens = vec![];
    for a in 0..n {
        for b in a + 1..n {
            if seen[pid(a, b)] {
                continue;
            }
            seen[pid(a, b)] = true;
            let mut orb = vec![(a, b)];
            let mut i = 0;
            while i < orb.len() {
                let (x, y) = orb[i];
                for g in &gens {
                    let (u, v) = (g.0[x] as usize, g.0[y] as usize);
                    if !seen[pid(u, v)] {
                        seen[pid(u, v)] = true;
                        orb.push((u, v));
                    }
                }
                i += 1;
            }
            plens.push(orb.len() as u64);
        }
    }
    plens.sort_unstable();
    k.push(u64::MAX);
    k.extend(plens);
    k
}

/// The elements x of the ambient group with H^x = H.
fn normalizer(t: &Table, h: &Sub) -> Vec<u32> {
    (0..t.order as u32).filter(|&x| h.gens.iter().all(|&g| h.has(t.conj(g, x)))).collect()
}

/// Is K a conjugate of H (same order assumed)?
fn conjugate(t: &Table, h: &Sub, k: &Sub) -> bool {
    if h.gens.is_empty() {
        return k.size == 1;
    }
    let g0 = h.gens[0];
    let c0 = t.ctype[g0 as usize];
    (0..t.order as u32).any(|x| {
        let y = t.conj(g0, x);
        t.ctype[y as usize] == c0 && k.has(y) && h.gens[1..].iter().all(|&g| k.has(t.conj(g, x)))
    })
}

/// The subgroup generated by `gens` (closure by multiplication).
fn closure(t: &Table, gens: &[u32]) -> Sub {
    let mut s = Sub::trivial(t.order);
    let mut list = vec![0u32];
    let mut i = 0;
    while i < list.len() {
        for &g in gens {
            let y = t.mul(list[i], g);
            if s.set(y) {
                list.push(y);
            }
        }
        i += 1;
    }
    s.size = list.len();
    s.gens = gens.to_vec();
    s
}

fn prime_factor_count(o: &sagebrush_bigint::BigInt) -> usize {
    use num_traits::ToPrimitive;
    let mut m = match o.to_u128() {
        Some(m) => m,
        None => return 99,
    };
    let mut c = 0;
    let mut d = 2u128;
    while d * d <= m {
        if m % d == 0 {
            c += 1;
            while m % d == 0 {
                m /= d;
            }
        }
        d += 1;
    }
    c + (m > 1) as usize
}

fn q_order(s: &Sub) -> sagebrush_bigint::BigInt {
    sagebrush_bigint::BigInt::from(s.size as u64)
}

fn is_prime(k: usize) -> bool {
    k >= 2 && (2..k).take_while(|d| d * d <= k).all(|d| k % d != 0)
}

/// The classes of subgroups, as (representative, class key).
pub struct Lattice {
    pub table: Table,
    pub classes: Vec<Sub>,
    keys: FnvMap<Vec<u64>, Vec<usize>>,
}

impl Lattice {
    fn add(&mut self, s: Sub) -> Option<usize> {
        let k = key(&self.table, &s);
        if let Some(cands) = self.keys.get(&k) {
            for &c in cands {
                if conjugate(&self.table, &s, &self.classes[c]) {
                    return None;
                }
            }
        }
        self.classes.push(s);
        let i = self.classes.len() - 1;
        self.keys.entry(k).or_default().push(i);
        Some(i)
    }

    /// All conjugacy classes of subgroups of g.
    pub fn new(g: &Group, limit: usize) -> Result<Lattice, String> {
        let table = Table::new(g, limit)?;
        let order = table.order;
        let mut lat = Lattice { table, classes: vec![], keys: FnvMap::default() };
        let mut queue = vec![];
        if let Some(i) = lat.add(Sub::trivial(order)) {
            queue.push(i);
        }
        // the perfect subgroups: those generated by an involution and one
        // more element, then closed under Q -> the perfect core of <Q, z>
        // (perfect groups that are not simple need not be generated by an
        // involution and one element, e.g. 2^5:A5 in S2 wr S6)
        let mut perfect: Vec<usize> = vec![];
        for p in perfect_subgroups(&lat.table, g) {
            if let Some(i) = lat.add(p) {
                queue.push(i);
                perfect.push(i);
            }
        }
        let mut pi = 0;
        while pi < perfect.len() {
            sagebrush_interrupt::check();
            let q = lat.classes[perfect[pi]].clone();
            pi += 1;
            let nq = normalizer(&lat.table, &q);
            let ngens = small_generating_set(&lat.table, &nq);
            let qperms: Vec<Perm> = q.gens.iter().map(|&x| lat.table.perm(x)).collect();
            // z in N(Q) gives <Q, z> with Q normal and a cyclic quotient: core Q
            let mut seen = q.clone();
            for &x in &nq {
                seen.set(x);
            }
            for z in 0..lat.table.order as u32 {
                if seen.has(z) {
                    continue;
                }
                // one z from each orbit of N(Q) acting by conjugation
                let mut orb = vec![z];
                seen.set(z);
                let mut k = 0;
                while k < orb.len() {
                    for &c in &ngens {
                        let w = lat.table.conj(orb[k], c);
                        if !seen.has(w) {
                            seen.set(w);
                            orb.push(w);
                        }
                    }
                    k += 1;
                }
                let mut gens = qperms.clone();
                gens.push(lat.table.perm(z));
                let h = Group::new(lat.table.n, gens).unwrap();
                let core = h.derived_series().pop().unwrap();
                if core.is_trivial() || core.order() == q_order(&q) {
                    continue;
                }
                let cg: Vec<u32> = core.gens.iter().map(|p| lat.table.lookup(p).unwrap()).collect();
                let s = closure(&lat.table, &cg);
                if let Some(i) = lat.add(s) {
                    queue.push(i);
                    perfect.push(i);
                }
            }
        }
        while let Some(ci) = queue.pop() {
            sagebrush_interrupt::check();
            let h = lat.classes[ci].clone();
            let nn = normalizer(&lat.table, &h);
            let mut covered = h.clone();
            for &g0 in &nn {
                if covered.has(g0) {
                    continue;
                }
                // the order of g0 modulo H
                let mut k = 1;
                let mut y = g0;
                while !h.has(y) {
                    y = lat.table.mul(y, g0);
                    k += 1;
                }
                if !is_prime(k) {
                    continue;
                }
                // K = H u Hg u ... u Hg^(k-1)
                let mut kk = h.clone();
                let hel = h.elements();
                let mut gi = g0;
                for _ in 1..k {
                    for &e in &hel {
                        let z = lat.table.mul(e, gi);
                        kk.set(z);
                        covered.set(z);
                    }
                    gi = lat.table.mul(gi, g0);
                }
                kk.size = h.size * k;
                kk.gens = h.gens.clone();
                kk.gens.push(g0);
                if let Some(i) = lat.add(kk) {
                    queue.push(i);
                }
            }
        }
        lat.classes.sort_by_key(|s| s.size);
        // rebuild the key index for the new order
        let mut keys: FnvMap<Vec<u64>, Vec<usize>> = FnvMap::default();
        for (i, s) in lat.classes.iter().enumerate() {
            keys.entry(key(&lat.table, s)).or_default().push(i);
        }
        lat.keys = keys;
        Ok(lat)
    }

    /// A class representative as a Group.
    pub fn group(&self, i: usize) -> Group {
        let gens: Vec<Perm> = self.classes[i].gens.iter().map(|&g| self.table.perm(g)).collect();
        Group::new(self.table.n, gens).unwrap()
    }

    /// Is some conjugate of class i contained in class j?
    pub fn contained(&self, i: usize, j: usize) -> bool {
        let (h, k) = (&self.classes[i], &self.classes[j]);
        if h.size > k.size || k.size % h.size != 0 {
            return false;
        }
        if h.gens.is_empty() {
            return true;
        }
        let t = &self.table;
        (0..t.order as u32).any(|x| h.gens.iter().all(|&g| k.has(t.conj(g, x))))
    }
}

/// The nontrivial perfect subgroups (not up to conjugacy): those generated
/// by an involution (one of each cycle type, the classes of Sym(n)
/// meeting g) and another element, that are perfect.
fn perfect_subgroups(t: &Table, g: &Group) -> Vec<Sub> {
    // one involution from each conjugacy class of g (classes of the
    // ambient group, which can be finer than cycle types), even ones only
    let ggens: Vec<u32> = g.gens.iter().map(|p| t.lookup(p).unwrap()).collect();
    let mut invs: Vec<u32> = vec![];
    let mut done = vec![false; t.order];
    for i in 0..t.order as u32 {
        if done[i as usize] {
            continue;
        }
        let p = t.perm(i);
        if p.is_identity() || p.sign() != 1 || !p.cycle_type().iter().all(|&l| l <= 2) {
            continue;
        }
        invs.push(i);
        let mut orb = vec![i];
        done[i as usize] = true;
        let mut k = 0;
        while k < orb.len() {
            for &c in &ggens {
                let z = t.conj(orb[k], c);
                if !done[z as usize] {
                    done[z as usize] = true;
                    orb.push(z);
                }
            }
            k += 1;
        }
    }
    let mut out: Vec<Sub> = vec![];
    let mut found: std::collections::HashSet<Vec<u64>> = std::collections::HashSet::new();
    for &x in &invs {
        // <x, y> and <x, y^c> are conjugate for c centralizing x: one y from
        // each orbit of the centralizer acting by conjugation
        let cent: Vec<u32> = (0..t.order as u32).filter(|&c| t.conj(x, c) == x).collect();
        let cgens = small_generating_set(t, &cent);
        let mut seen = vec![false; t.order];
        for y in 0..t.order as u32 {
            sagebrush_interrupt::check();
            if seen[y as usize] {
                continue;
            }
            // mark the orbit of y
            let mut orb = vec![y];
            seen[y as usize] = true;
            let mut i = 0;
            while i < orb.len() {
                for &c in &cgens {
                    let z = t.conj(orb[i], c);
                    if !seen[z as usize] {
                        seen[z as usize] = true;
                        orb.push(z);
                    }
                }
                i += 1;
            }
            if t.perm(y).sign() != 1 || y == x || y == 0 {
                continue;
            }
            let h = Group::new(t.n, vec![t.perm(x), t.perm(y)]).unwrap();
            let o = h.order();
            // a nontrivial perfect group's order has at least three prime
            // factors (Burnside: groups of order p^a q^b are solvable)
            if prime_factor_count(&o) < 3 {
                continue;
            }
            if h.derived_subgroup().order() != o {
                continue;
            }
            let s = closure(t, &[x, y]);
            if found.insert(s.bits.clone()) {
                out.push(s);
            }
        }
    }
    out
}

/// A few elements generating the same group as `els` (a subgroup's elements).
fn small_generating_set(t: &Table, els: &[u32]) -> Vec<u32> {
    let mut gens: Vec<u32> = vec![];
    let mut sub = closure(t, &[]);
    for &e in els {
        if sub.size == els.len() {
            break;
        }
        if !sub.has(e) {
            gens.push(e);
            sub = closure(t, &gens);
        }
    }
    gens
}

/// The transitive groups of degree n (n <= 9), up to conjugacy in Sym(n),
/// smallest first: the transitive classes of subgroups of Sym(n).
pub fn transitive_groups_small(n: usize) -> Result<Vec<Group>, String> {
    if n > 9 {
        return Err("transitive_groups_small is for degree at most 9".into());
    }
    let s = crate::named::symmetric(n);
    if n <= 1 {
        return Ok(vec![s]);
    }
    let lat = Lattice::new(&s, 400_000)?;
    Ok((0..lat.classes.len()).map(|i| lat.group(i)).filter(|g| g.is_transitive()).collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::named::symmetric;

    #[test]
    fn subgroup_classes_of_symmetric_groups() {
        // the numbers of conjugacy classes of subgroups of S_n (OEIS A000638)
        for (n, want) in [(2, 2usize), (3, 4), (4, 11), (5, 19), (6, 56), (7, 96), (8, 296)] {
            let lat = Lattice::new(&symmetric(n), 50_000).unwrap();
            assert_eq!(lat.classes.len(), want, "S{}", n);
        }
    }

    #[test]
    fn transitive_counts() {
        // the numbers of transitive groups of degree n (OEIS A002106)
        for (n, want) in [(2, 1usize), (3, 2), (4, 5), (5, 5), (6, 16), (7, 7), (8, 50)] {
            assert_eq!(transitive_groups_small(n).unwrap().len(), want, "degree {}", n);
        }
    }
}
