//! Standard permutation groups.  Points are 0..n-1; a projective line
//! P^1(F_p) is 0..p-1 with infinity = p.

use crate::group::Group;
use crate::perm::Perm;

fn cyc(n: usize, c: &[u32]) -> Perm {
    Perm::from_cycles(n, &[c.to_vec()]).unwrap()
}

/// Sym(n)
pub fn symmetric(n: usize) -> Group {
    if n < 2 {
        return Group::trivial(n);
    }
    let all: Vec<u32> = (0..n as u32).collect();
    Group::new(n, vec![cyc(n, &[0, 1]), cyc(n, &all)]).unwrap()
}

/// Alt(n)
pub fn alternating(n: usize) -> Group {
    if n < 3 {
        return Group::trivial(n);
    }
    // a 3-cycle and an n-cycle (n odd) or (n-1)-cycle (n even)
    let long: Vec<u32> = if n % 2 == 1 { (0..n as u32).collect() } else { (1..n as u32).collect() };
    Group::new(n, vec![cyc(n, &[0, 1, 2]), cyc(n, &long)]).unwrap()
}

/// C_n, regular
pub fn cyclic(n: usize) -> Group {
    let all: Vec<u32> = (0..n as u32).collect();
    if n < 2 {
        return Group::trivial(n);
    }
    Group::new(n, vec![cyc(n, &all)]).unwrap()
}

/// The dihedral group of order 2n, on the vertices of an n-gon.
pub fn dihedral(n: usize) -> Group {
    if n < 3 {
        // as Sage: order 2n on max(n, 2) points... keep it simple
        return match n {
            2 => Group::new(4, vec![cyc(4, &[0, 1]), cyc(4, &[2, 3])]).unwrap(),
            _ => Group::new(2, vec![cyc(2, &[0, 1])]).unwrap(),
        };
    }
    let all: Vec<u32> = (0..n as u32).collect();
    let refl = Perm((0..n as u32).map(|x| (n as u32 - x) % n as u32).collect());
    Group::new(n, vec![cyc(n, &all), refl]).unwrap()
}

pub fn is_prime(p: u64) -> bool {
    p >= 2 && (2..).take_while(|d| d * d <= p).all(|d| p % d != 0)
}

fn primitive_root(p: u64) -> u64 {
    let mut fs = vec![];
    let mut m = p - 1;
    let mut d = 2;
    while d * d <= m {
        if m % d == 0 {
            fs.push(d);
            while m % d == 0 {
                m /= d;
            }
        }
        d += 1;
    }
    if m > 1 {
        fs.push(m);
    }
    (2..p).find(|&g| fs.iter().all(|&q| powmod(g, (p - 1) / q, p) != 1)).unwrap_or(1)
}

fn powmod(mut b: u64, mut e: u64, m: u64) -> u64 {
    let mut r = 1u64;
    b %= m;
    while e > 0 {
        if e & 1 == 1 {
            r = r * b % m;
        }
        b = b * b % m;
        e >>= 1;
    }
    r
}

/// x -> f(x) on P^1(F_p), infinity = p; f returns None for infinity.
fn moebius(p: u64, f: impl Fn(Option<u64>) -> Option<u64>) -> Perm {
    let enc = |x: Option<u64>| x.unwrap_or(p) as u32;
    Perm((0..=p).map(|x| enc(f(if x == p { None } else { Some(x) }))).collect())
}

fn inv_mod(a: u64, p: u64) -> u64 {
    powmod(a, p - 2, p)
}

/// AGL(1, p) = {x -> ax + b}, of order p(p-1), on F_p
pub fn agl1(p: u64) -> Result<Group, String> {
    if !is_prime(p) {
        return Err(format!("{} is not prime", p));
    }
    let g = primitive_root(p);
    let n = p as usize;
    let t = Perm((0..p).map(|x| ((x + 1) % p) as u32).collect());
    let m = Perm((0..p).map(|x| (x * g % p) as u32).collect());
    Group::new(n, vec![t, m])
}

/// PSL(2, p) or PGL(2, p) on the p+1 points of the projective line
pub fn pl2(p: u64, projective_general: bool) -> Result<Group, String> {
    if !is_prime(p) {
        return Err(format!("{} is not prime (only prime fields here)", p));
    }
    let g = primitive_root(p);
    let a = if projective_general { g } else { g * g % p };
    let t = moebius(p, |x| x.map(|x| (x + 1) % p));
    let m = moebius(p, |x| x.map(|x| x * a % p));
    let s = moebius(p, |x| match x {
        None => Some(0),
        Some(0) => None,
        Some(x) => Some((p - inv_mod(x, p)) % p),
    });
    Group::new(p as usize + 1, vec![t, m, s])
}

/// The Mathieu groups M11, M12, M22, M23, M24.
///
/// M24 is Conway's construction on P^1(F_23): generated by PSL(2, 23)
/// (x -> x + 1, x -> 2x, x -> -1/x) and x -> x^3/9 on the nonzero squares,
/// 9x^3 on the non-squares (fixing 0 and infinity).  M23 and M22 are its
/// point stabilizers.  M11 = <(1,...,11), (3,7,11,8)(4,10,5,6)> and M12
/// adds (1,12)(2,11)(3,6)(4,8)(5,9)(7,10) (points numbered from 1).  The
/// orders are checked by the tests (and are proven by the stabilizer chain).
pub fn mathieu(n: usize) -> Result<Group, String> {
    let from1 = |deg: usize, cs: &[&[u32]]| Perm::from_cycles(deg, &cs.iter().map(|c| c.iter().map(|x| x - 1).collect()).collect::<Vec<_>>()).unwrap();
    match n {
        11 | 12 => {
            let deg = n;
            let mut gens = vec![
                from1(deg, &[&[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]),
                from1(deg, &[&[3, 7, 11, 8], &[4, 10, 5, 6]]),
            ];
            if n == 12 {
                gens.push(from1(deg, &[&[1, 12], &[2, 11], &[3, 6], &[4, 8], &[5, 9], &[7, 10]]));
            }
            Group::new(deg, gens)
        }
        22 | 23 | 24 => {
            let p = 23u64;
            let sq: Vec<bool> = {
                let mut s = vec![false; p as usize];
                for x in 1..p {
                    s[(x * x % p) as usize] = true;
                }
                s
            };
            let ninth = inv_mod(9, p);
            let t = moebius(p, |x| x.map(|x| (x + 1) % p));
            let m = moebius(p, |x| x.map(|x| x * 2 % p));
            let s = moebius(p, |x| match x {
                None => Some(0),
                Some(0) => None,
                Some(x) => Some((p - inv_mod(x, p)) % p),
            });
            let d = moebius(p, |x| match x {
                None => None,
                Some(0) => Some(0),
                Some(x) => {
                    let c = x * x % p * x % p;
                    Some(if sq[x as usize] { c * ninth % p } else { 9 * c % p })
                }
            });
            let m24 = Group::new(24, vec![t, m, s, d])?;
            if n == 24 {
                return Ok(m24);
            }
            // M23 fixes infinity (23); M22 also fixes 22: restrict the generators
            let fixed: Vec<u32> = if n == 23 { vec![23] } else { vec![23, 22] };
            let st = m24.pointwise_stabilizer(&fixed);
            let gens: Vec<Perm> = st.gens.iter().map(|g| Perm(g.0[..n].to_vec())).collect();
            Group::new(n, gens)
        }
        _ => Err(format!("there is no Mathieu group M{}", n)),
    }
}
