[package]
name = "sagebrush-py"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "sagebrush_native"
crate-type = ["cdylib"]

[dependencies]
sagebrush-modsym = { path = "../modsym" }
sagebrush-ap = { path = "../ap" }
sagebrush-web = { path = "../web" }
rayon = "1.10"
pyo3 = { version = "0.27", features = ["extension-module", "num-bigint"] }
num-bigint = "0.4"
