[package]
name = "sagebrush-app"
version = "0.2.0"
description = "Sagebrush: Python, Sage and Magma notebooks with Sagebrush's math engines"
authors = ["SageMath, Inc."]
license = "MIT OR Apache-2.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-localhost = "2"
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
