[package]
name = "sagebrush-node"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "sagebrush_node"
crate-type = ["cdylib"]

[dependencies]
sagebrush-bigint = { path = "../bigint" }
sagebrush-modsym = { path = "../modsym" }
sagebrush-ap = { path = "../ap" }
rayon = "1.10"
napi = { version = "2", default-features = false, features = ["napi6"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
