[package]
name = "sagebrush-modsym"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
sagebrush-bigint = { path = "../bigint" }
sagebrush-interrupt = { path = "../interrupt" }
rayon = { version = "1.10", optional = true }
num-traits = "0.2"
sagebrush-poly = { path = "../poly" }

[dev-dependencies]
sagebrush-ap = { path = "../ap" }
serde_json = "1"
