"""Write magma_online_1.m and magma_online_2.m: the Groebner basis
benchmarks of articles/groebner as Magma scripts (explicit generators from
sage.rings.ideal.Katsura / Cyclic, as our runs used), each with a
calibration block for the machine.

Run them on a current Magma and on the local Magma 2.18, and compare the
lines.  The online calculator (https://magma.maths.usyd.edu.au/calc/,
V2.29-10) stops a calculation after 60 s and takes at most 50000 bytes, so
the cases come in two parts: part 2 is katsura-7 lex over QQ alone (29 s
in Magma 2.18).  bench/groebner/sagebrush_bench.sage runs the same cases
in Sagebrush.

    PYTHONPATH=engine/py/python:lib python3 bench/groebner/make_magma_online.py
"""
import os

import sagebrush.sage  # noqa: F401  (the Sage layer)
import _sage_shim

_sage_shim.install()
from sagebrush.sage import *  # noqa: E402,F401,F403
import sage  # noqa: E402

CASES = [
    # (family, n, field, order): degrevlex mod p, over QQ, then lex
    ("Cyclic", 7, "32003", "grevlex"),
    ("Katsura", 9, "32003", "grevlex"),
    ("Katsura", 10, "32003", "grevlex"),
    ("Cyclic", 8, "32003", "grevlex"),
    ("Katsura", 8, "QQ", "grevlex"),
    ("Cyclic", 7, "QQ", "grevlex"),
    ("Katsura", 9, "QQ", "grevlex"),
    ("Katsura", 8, "32003", "lex"),
    ("Katsura", 9, "32003", "lex"),
    ("Cyclic", 7, "32003", "lex"),
    ("Katsura", 6, "QQ", "lex"),
    ("Katsura", 7, "QQ", "lex"),
]

# the machine: big-integer arithmetic (GMP) and the interpreter, whose
# algorithms do not change between Magma versions the way Groebner bases do
CALIBRATION = """// calibration: big-integer arithmetic (GMP) and the interpreter, to compare machines
t := Cputime(); x := 3^5000000; for k in [1..4] do y := x*x; z := y div (x + 1); end for; printf "calibration GMP: %o s\\n", Cputime(t);
t := Cputime(); s := 0; for i in [1..2000000] do s +:= (i*i) mod 7; end for; printf "calibration loop: %o s\\n", Cputime(t);
procedure bench(name, I)
  t := Cputime(); w := Realtime();
  G := GroebnerBasis(I);
  printf "%o: %o elements, cpu %o s, wall %o s\\n", name, #G, Cputime(t), Realtime(w);
end procedure;"""


def script(cases, part):
    out = [
        "// Groebner basis benchmarks (sagebrush articles/groebner), part %d; generated by" % part,
        "// bench/groebner/make_magma_online.py.  Each line: name, #basis, CPU and wall seconds.",
        'a, b, c := GetVersion(); printf "Magma %o.%o-%o\\n", a, b, c;',
        CALIBRATION,
    ]
    for fam, n, field, order in cases:
        nv = n + 1 if fam == "Katsura" else n
        K = QQ if field == "QQ" else GF(int(field))
        R = PolynomialRing(K, "x", nv)
        I = getattr(sage.rings.ideal, fam)(R)
        gens = ", ".join(str(g).replace(" ", "") for g in I.gens())
        mk = "Rationals()" if field == "QQ" else "GF(%s)" % field
        name = "%s-%d %s %s" % (fam.lower(), n, "QQ" if field == "QQ" else "GF(" + field + ")", order)
        out.append('P<%s> := PolynomialRing(%s, %d, "%s");' % (",".join("x%d" % i for i in range(nv)), mk, nv, order))
        out.append('bench("%s", ideal<P | %s>);' % (name, gens))
    return "\n".join(out) + "\n"


here = os.path.dirname(os.path.abspath(__file__))
for part, cases in ((1, CASES[:-1]), (2, CASES[-1:])):
    with open(os.path.join(here, "magma_online_%d.m" % part), "w") as f:
        f.write(script(cases, part))
