// @generated by pyparse/gen/build.py from CPython v3.14.4 (Grammar/Tokens); do not edit.

export const ENDMARKER = 0;
export const NAME = 1;
export const NUMBER = 2;
export const STRING = 3;
export const NEWLINE = 4;
export const INDENT = 5;
export const DEDENT = 6;
export const LPAR = 7;
export const RPAR = 8;
export const LSQB = 9;
export const RSQB = 10;
export const COLON = 11;
export const COMMA = 12;
export const SEMI = 13;
export const PLUS = 14;
export const MINUS = 15;
export const STAR = 16;
export const SLASH = 17;
export const VBAR = 18;
export const AMPER = 19;
export const LESS = 20;
export const GREATER = 21;
export const EQUAL = 22;
export const DOT = 23;
export const PERCENT = 24;
export const LBRACE = 25;
export const RBRACE = 26;
export const EQEQUAL = 27;
export const NOTEQUAL = 28;
export const LESSEQUAL = 29;
export const GREATEREQUAL = 30;
export const TILDE = 31;
export const CIRCUMFLEX = 32;
export const LEFTSHIFT = 33;
export const RIGHTSHIFT = 34;
export const DOUBLESTAR = 35;
export const PLUSEQUAL = 36;
export const MINEQUAL = 37;
export const STAREQUAL = 38;
export const SLASHEQUAL = 39;
export const PERCENTEQUAL = 40;
export const AMPEREQUAL = 41;
export const VBAREQUAL = 42;
export const CIRCUMFLEXEQUAL = 43;
export const LEFTSHIFTEQUAL = 44;
export const RIGHTSHIFTEQUAL = 45;
export const DOUBLESTAREQUAL = 46;
export const DOUBLESLASH = 47;
export const DOUBLESLASHEQUAL = 48;
export const AT = 49;
export const ATEQUAL = 50;
export const RARROW = 51;
export const ELLIPSIS = 52;
export const COLONEQUAL = 53;
export const EXCLAMATION = 54;
export const OP = 55;
export const TYPE_IGNORE = 56;
export const TYPE_COMMENT = 57;
export const SOFT_KEYWORD = 58;
export const FSTRING_START = 59;
export const FSTRING_MIDDLE = 60;
export const FSTRING_END = 61;
export const TSTRING_START = 62;
export const TSTRING_MIDDLE = 63;
export const TSTRING_END = 64;
export const COMMENT = 65;
export const NL = 66;
export const ERRORTOKEN = 67;
export const ENCODING = 68;
export const N_TOKENS = 69;
export const TOKEN_NAMES: string[] = ["ENDMARKER", "NAME", "NUMBER", "STRING", "NEWLINE", "INDENT", "DEDENT", "LPAR", "RPAR", "LSQB", "RSQB", "COLON", "COMMA", "SEMI", "PLUS", "MINUS", "STAR", "SLASH", "VBAR", "AMPER", "LESS", "GREATER", "EQUAL", "DOT", "PERCENT", "LBRACE", "RBRACE", "EQEQUAL", "NOTEQUAL", "LESSEQUAL", "GREATEREQUAL", "TILDE", "CIRCUMFLEX", "LEFTSHIFT", "RIGHTSHIFT", "DOUBLESTAR", "PLUSEQUAL", "MINEQUAL", "STAREQUAL", "SLASHEQUAL", "PERCENTEQUAL", "AMPEREQUAL", "VBAREQUAL", "CIRCUMFLEXEQUAL", "LEFTSHIFTEQUAL", "RIGHTSHIFTEQUAL", "DOUBLESTAREQUAL", "DOUBLESLASH", "DOUBLESLASHEQUAL", "AT", "ATEQUAL", "RARROW", "ELLIPSIS", "COLONEQUAL", "EXCLAMATION", "OP", "TYPE_IGNORE", "TYPE_COMMENT", "SOFT_KEYWORD", "FSTRING_START", "FSTRING_MIDDLE", "FSTRING_END", "TSTRING_START", "TSTRING_MIDDLE", "TSTRING_END", "COMMENT", "NL", "ERRORTOKEN", "ENCODING"];
export const EXACT_TOKENS: Record<string, number> = {
  '(': 7,
  ')': 8,
  '[': 9,
  ']': 10,
  ':': 11,
  ',': 12,
  ';': 13,
  '+': 14,
  '-': 15,
  '*': 16,
  '/': 17,
  '|': 18,
  '&': 19,
  '<': 20,
  '>': 21,
  '=': 22,
  '.': 23,
  '%': 24,
  '{': 25,
  '}': 26,
  '==': 27,
  '!=': 28,
  '<=': 29,
  '>=': 30,
  '~': 31,
  '^': 32,
  '<<': 33,
  '>>': 34,
  '**': 35,
  '+=': 36,
  '-=': 37,
  '*=': 38,
  '/=': 39,
  '%=': 40,
  '&=': 41,
  '|=': 42,
  '^=': 43,
  '<<=': 44,
  '>>=': 45,
  '**=': 46,
  '//': 47,
  '//=': 48,
  '@': 49,
  '@=': 50,
  '->': 51,
  '...': 52,
  ':=': 53,
  '!': 54,
};
