// Build the Rust WebAssembly kernels (kernels/) and embed them as base64 in
// src/runtime/kernels_wasm.ts, which is committed so that building
// sagebrush does not require Rust.  Run: node scripts/build-kernels.mjs
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
// the main module (simd128), and exp/log with relaxed SIMD (kernels/relaxed)
function build(dir, name, features) {
  execFileSync("cargo", ["build", "--release", "--target", "wasm32-unknown-unknown"], {
    cwd: join(root, dir),
    stdio: "inherit",
    env: { ...process.env, RUSTFLAGS: `-C target-feature=${features}` },
  });
  const wasm = readFileSync(join(root, dir, `target/wasm32-unknown-unknown/release/${name}.wasm`));
  new WebAssembly.Module(wasm); // validate
  return wasm;
}
const main = build("kernels", "sagebrush_kernels", "+simd128");
const relaxed = build("kernels/relaxed", "sagebrush_kernels_relaxed", "+simd128,+relaxed-simd");
const literal = (wasm) => wasm.toString("base64").match(/.{1,100}/g).map((l) => `  "${l}"`).join(" +\n");
writeFileSync(
  join(root, "src/runtime/kernels_wasm.ts"),
  `// Generated by scripts/build-kernels.mjs from kernels/; do not edit.\n` +
    `export const KERNELS_WASM =\n${literal(main)};\n` +
    `export const KERNELS_RELAXED_WASM =\n${literal(relaxed)};\n`,
);
console.log(`kernels: ${main.length} bytes; relaxed: ${relaxed.length} bytes`);
