// Build the Rust WebAssembly kernels (kernels/) and embed them as base64 in
// src/runtime/kernels_wasm.ts, which is committed so that building
// sagebrush does not require Rust.  Run: node scripts/build-kernels.mjs
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "kernels");
execFileSync("cargo", ["build", "--release", "--target", "wasm32-unknown-unknown"], {
  cwd: dir,
  stdio: "inherit",
  env: { ...process.env, RUSTFLAGS: "-C target-feature=+simd128" },
});
const wasm = readFileSync(join(dir, "target/wasm32-unknown-unknown/release/sagebrush_kernels.wasm"));
new WebAssembly.Module(wasm); // validate
const b64 = wasm.toString("base64");
const lines = b64.match(/.{1,100}/g).map((l) => `  "${l}"`).join(" +\n");
writeFileSync(
  join(root, "src/runtime/kernels_wasm.ts"),
  `// Generated by scripts/build-kernels.mjs from kernels/src/lib.rs; do not edit.\n` +
    `export const KERNELS_WASM =\n${lines};\n`,
);
console.log(`kernels: ${wasm.length} bytes`);
