//! Class groups of imaginary quadratic orders of fundamental discriminant
//! D < 0 (|D| < 2^200: the sieve's values must fit in i128), assuming GRH:
//! the factor base holds the primes up to c log^2 |D| (c = 15/4, Grenie and
//! Molteni's improvement of Bach's 6), which generate the group; relations come from the sieve (relations.rs); the
//! group is Z^n / L for the relation lattice L, whose determinant is h once
//! it is below sqrt 2 times the analytic estimate of h (the true h is above
//! 1/sqrt 2 times it, and det L is a multiple of h).

use crate::arith::*;
use crate::linalg::{cokernel, det_crt_probable, eliminate, hnf_mod, hnf_mod_until, independent_rows, smith, ModD, ModD128, Reduced};
use crate::relations::{collect, FactorBase, Params, Stats};
use sagebrush_bigint::BigInt;
use num_integer::Integer;
use num_traits::{One, Signed, ToPrimitive, Zero};

#[derive(Debug, Clone, PartialEq)]
pub struct ClassGroup {
    pub h: BigInt,
    /// The invariants d_1 >= d_2 >= ... (d_{i+1} | d_i), as PARI's .cyc.
    pub cyc: Vec<BigInt>,
}

#[derive(Debug, Default)]
pub struct Timing {
    pub fb: usize,
    pub relations: usize,
    pub core: usize,
    pub rounds: usize,
    pub sieve_s: f64,
    pub linalg_s: f64,
    pub h_est: f64,
    pub polys: u64,
}

/// h estimated by the analytic class number formula h = sqrt|D| L(1, chi) / pi
/// (|D| > 4), with L(1, chi) from Bach's weighted average of the truncated
/// Euler products P(i) = prod_{p <= i} (1 - chi(p)/p)^-1 over x <= i < 2x,
/// weights i log i: much more accurate than a single truncation.
pub fn h_estimate(d: &BigInt, x: u64) -> f64 {
    (-d.to_f64().unwrap()).sqrt() / std::f64::consts::PI * l1_estimate(d, x)
}

/// L(1, chi_D) by Bach's weighted average of truncated Euler products (see
/// h_estimate).
pub fn l1_estimate(d: &BigInt, x: u64) -> f64 {
    let d8 = bigmod(d, 8);
    static SMALL: std::sync::OnceLock<Vec<u64>> = std::sync::OnceLock::new();
    let cached = SMALL.get_or_init(|| primes_up_to(1 << 17));
    let x = x.max(2);
    let fresh;
    let primes: &[u64] = if 2 * x <= 1 << 17 {
        cached
    } else {
        fresh = primes_up_to(2 * x);
        &fresh
    };
    let mut log_p = 0.0f64; // log P(i)
    let mut k = 0;
    let (mut num, mut den) = (0.0f64, 0.0f64);
    for i in 1..2 * x {
        while k < primes.len() && primes[k] <= i {
            let p = primes[k];
            log_p -= (1.0 - kronecker_res(d8, bigmod(d, p), p) as f64 / p as f64).ln();
            k += 1;
        }
        if i >= x {
            let w = i as f64 * (i as f64).ln();
            num += w * log_p;
            den += w;
        }
    }
    (num / den).exp()
}

pub(crate) struct Tuning {
    pub sieve: Params,
    /// relations to collect before the first linear algebra, per prime
    pub excess: f64,
    /// the heaviest pivot row structured elimination may use
    pub pivot_weight: usize,
}

pub(crate) fn tuning(digits: f64, bound: u64) -> Tuning {
    let m = if digits < 16.0 { 1 << 9 } else { 1 << 11 };
    // sieving with the primes up to a fraction of the bound: the others
    // enter relations as prime cofactors (and as forced q's for coverage).
    // A larger fraction finds relations faster but leaves a larger dense
    // core for the linear algebra.
    let frac = if digits < 30.0 { 0.1 } else if digits < 36.0 { 0.15 } else { 0.2 };
    let sieve_bound = ((frac * bound as f64) as u64).max(bound.min(500));
    let sieve = Params { m, small: 30, lp_mult: 40, slack: 0, sieve_bound };
    Tuning { sieve, excess: 1.4, pivot_weight: 80 }
}

/// The class group of the imaginary quadratic order of discriminant d (a
/// fundamental discriminant d < 0), assuming GRH.
pub fn class_group(d: &BigInt) -> Result<(ClassGroup, Timing), String> {
    let d4 = bigmod(d, 4);
    if !d.is_negative() || !(d4 == 0 || d4 == 1) {
        return Err(format!("{} is not a negative discriminant", d));
    }
    if d.bits() > 200 {
        return Err("|D| >= 2^200 is not supported yet".into());
    }
    let absd = -d.to_f64().unwrap();
    let ld = absd.ln();
    if absd < 5.0 {
        return Ok((ClassGroup { h: BigInt::one(), cyc: vec![] }, Timing::default()));
    }
    if absd < SMALL_D {
        let fb = FactorBase::new(d, ((23.0 / 6.0 * ld * ld).ceil() as u64).max(10));
        return Ok((small_group(d, &fb), Timing::default()));
    }
    let debug = std::env::var("QCL_DEBUG").is_ok();
    let mut tm = Timing::default();
    // Under GRH the class group is generated by the primes of norm at most
    // c log^2 |D|: Bach proved c = 6; Grenie and Molteni (Math. Comp. 2016)
    // c = 23/6 for quadratic fields, and 15/4 once |D| > 2.41e8.
    let c = if absd > 2.41e8 { 15.0 / 4.0 } else { 23.0 / 6.0 };
    let bound = (c * ld * ld).ceil() as u64;
    let fb = FactorBase::new(d, bound.max(60));
    let n = fb.primes.len();
    tm.fb = n;
    let t0 = crate::clock::Instant::now();
    // Bach's error term is O(log |D| / (sqrt x log x)): x of the order of
    // log^2 |D|.  Measured against 400 known class numbers up to 10^35,
    // even x = 256 stays within 4.2% (the acceptance window is 41%).
    let h_est = h_estimate(d, ((4.0 * ld * ld) as u64).clamp(1 << 10, 1 << 16));
    tm.h_est = h_est;
    let mut tu = tuning(absd.log10(), bound);
    if debug {
        eprintln!("setup (fb {} primes, h_est) {:.1} ms", n, t0.elapsed().as_secs_f64() * 1e3);
    }
    let mut rels = vec![];
    let mut stats = Stats { polys: 0, candidates: 0, full: 0, partial_pairs: 0 };
    let mut want = (tu.excess * n as f64) as usize + 20;
    let mut counts = vec![0u32; n];
    for round in 0..200 {
        sagebrush_interrupt::check();
        tm.rounds = round + 1;
        let t = crate::clock::Instant::now();
        let (found, _) = collect(&fb, want - rels.len(), &tu.sieve, round as u64 + 1, &mut stats, &mut counts);
        if found.is_empty() {
            // the small sieve base finds nothing for some forced prime
            tu.sieve.sieve_bound = u64::MAX;
        }
        rels.extend(found);
        tm.sieve_s += t.elapsed().as_secs_f64();
        let t = crate::clock::Instant::now();
        // relations to add if this round fails: a few per column lacking
        // one, else a fifth more
        let mut more = (rels.len() / 5).max(10);
        let found = match eliminate(n, &rels, tu.pivot_weight) {
            Reduced::Deficient(col) => {
                more = (4 * counts.iter().filter(|&&c| c == 0).count()).max(10);
                if debug {
                    eprintln!("round {} rels {}: column {} (p = {}) has no relation", round, rels.len(), col, fb.primes[col].p);
                }
                None
            }
            Reduced::Core(cols, dense) => {
                tm.core = cols.len();
                if debug {
                    eprintln!("round {} rels {}: core {} x {} after {:.1} ms", round, rels.len(), dense.len(), cols.len(), t.elapsed().as_secs_f64() * 1e3);
                }
                match core_group(&dense, cols.len(), h_est, round as u64, debug) {
                    Ok(g) => g,
                    Err(free) => {
                        // these primes lack independent relations: the
                        // next collection makes them its first q's
                        more = (4 * free.len()).max(10);
                        for j in free {
                            counts[cols[j]] = 0;
                        }
                        None
                    }
                }
            }
        };
        tm.linalg_s += t.elapsed().as_secs_f64();
        if let Some(g) = found {
            tm.relations = rels.len();
            tm.polys = stats.polys;
            return Ok((g, tm));
        }
        want = rels.len() + more;
    }
    Err("no convergence".into())
}

/// Below this |D| the group is computed exactly by small_group.
const SMALL_D: f64 = 100_000.0;

/// The class group by exhausting the subgroups generated by the prime forms
/// (Shanks): for each generator g, the least k with g^k in the subgroup H
/// generated so far gives the relation k e_g = (exponents of g^k); then
/// H grows to the union of g^i H, 0 <= i < k.  Exact; for small |D| only
/// (the table holds all h forms).
fn small_group(dd: &BigInt, fb: &FactorBase) -> ClassGroup {
    use crate::form::Form;
    // element -> exponents on the generators so far with k > 1
    let mut table: std::collections::HashMap<Form, Vec<u64>> = std::collections::HashMap::new();
    table.insert(Form::identity(&dd).reduced(), vec![]);
    let mut rels: Vec<Vec<i64>> = vec![];
    for fp in &fb.primes {
        let g = Form::new(BigInt::from(fp.p), BigInt::from(fp.b), &dd).reduced();
        let (mut x, mut k) = (g.clone(), 1u64);
        while !table.contains_key(&x) {
            x = x.compose(&g);
            k += 1;
        }
        if k == 1 {
            continue;
        }
        let j = rels.len();
        let mut row: Vec<i64> = table[&x].iter().map(|&e| -(e as i64)).collect();
        row.resize(j, 0);
        row.push(k as i64);
        rels.push(row);
        let old: Vec<(Form, Vec<u64>)> = table.iter().map(|(f, v)| (f.clone(), v.clone())).collect();
        let mut gi = g.clone();
        for i in 1..k {
            for (f, v) in &old {
                let mut v2 = v.clone();
                v2.resize(j, 0);
                v2.push(i);
                table.insert(f.compose(&gi), v2);
            }
            gi = gi.compose(&g);
        }
    }
    let r = rels.len();
    let m: Vec<Vec<BigInt>> = rels.iter().map(|row| (0..r).map(|t| BigInt::from(row.get(t).copied().unwrap_or(0))).collect()).collect();
    ClassGroup { h: BigInt::from(table.len()), cyc: smith(&m) }
}

/// Z^c / L for the lattice L spanned by `rows`, if its order is below
/// sqrt 2 h_est (so is h); None if L is not yet the full relation lattice;
/// the columns lacking a relation if L does not have full rank.
fn core_group(rows: &[Vec<i64>], c: usize, h_est: f64, seed: u64, debug: bool) -> Result<Option<ClassGroup>, Vec<usize>> {
    if c == 0 {
        return Ok(Some(ClassGroup { h: BigInt::one(), cyc: vec![] }));
    }
    let sel = independent_rows(rows, c).map_err(|free| {
        if debug {
            eprintln!("  not of full rank: {} free columns", free.len());
        }
        free
    })?;
    let Some((h, cyc)) = lattice_group(rows, c, &sel, None, h_est * std::f64::consts::SQRT_2, seed, debug) else { return Ok(None) };
    let ratio = h.to_f64().unwrap_or(f64::INFINITY) / h_est;
    if debug {
        eprintln!("  det/h_est {:.3}", ratio);
    }
    Ok((ratio <= std::f64::consts::SQRT_2).then(|| ClassGroup { h, cyc }))
}

/// The order and invariants of Z^c / L, L spanned by `rows` (of full rank,
/// `sel` c independent ones), by an HNF modulo a multiple of det L that
/// stops once the order is at most `enough`; `first_det` is det of the sel
/// rows if known.  None if no multiple of det L was found.
pub(crate) fn lattice_group(rows: &[Vec<i64>], c: usize, sel: &[usize], first_det: Option<BigInt>, enough: f64, seed: u64, debug: bool) -> Option<(BigInt, Vec<BigInt>)> {
    let t = crate::clock::Instant::now();
    let ms = || t.elapsed().as_secs_f64() * 1e3;
    // a multiple of det L: the gcd of the determinants of a few independent
    // square subsets, until it is word-sized
    let square = |sel: &[usize], from: &[Vec<i64>]| -> Vec<Vec<i64>> { sel.iter().map(|&k| from[k].clone()).collect() };
    let mut d0: BigInt = first_det.unwrap_or_else(|| det_crt_probable(&square(sel, rows))).abs();
    if debug {
        eprintln!("  first det {} bits at {:.1} ms", d0.bits(), ms());
    }
    for t in 1..4u64 {
        if t > 1 && d0.bits() < 62 {
            break;
        }
        // the rows in another order give another subset
        let mut order: Vec<usize> = (0..rows.len()).collect();
        let mut x = 0x2545_F491_4F6C_DD1Du64 ^ t ^ seed << 32;
        for i in (1..order.len()).rev() {
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            order.swap(i, (x % (i as u64 + 1)) as usize);
        }
        let shuffled = square(&order, rows);
        if let Ok(sel2) = independent_rows(&shuffled, c) {
            d0 = d0.gcd(&det_crt_probable(&square(&sel2, &shuffled)).abs());
        }
    }
    if debug {
        eprintln!("  det multiple {} bits at {:.1} ms", d0.bits(), ms());
    }
    if d0.is_zero() {
        return None;
    }
    // the independent rows first, so the HNF reaches full rank (and then
    // the early stop) quickly
    let mut used = vec![false; rows.len()];
    sel.iter().for_each(|&k| used[k] = true);
    let ordered: Vec<Vec<i64>> = sel.iter().chain((0..rows.len()).filter(|&k| !used[k]).collect::<Vec<_>>().iter()).map(|&k| rows[k].clone()).collect();
    let (h, red): (BigInt, _) = if d0 < BigInt::from(1u64 << 62) {
        let md = ModD::new(d0.to_u64().unwrap());
        let w = hnf_mod_until(&ordered, c, md, enough);
        ((0..c).map(|i| BigInt::from(w[i][i])).product(), cokernel(&w, md))
    } else if d0.bits() < 126 {
        let md = ModD128::new(d0.to_u128().unwrap());
        let w = hnf_mod_until(&ordered, c, md, enough);
        ((0..c).map(|i| BigInt::from(w[i][i])).product(), cokernel(&w, md))
    } else {
        let w = hnf_mod(&ordered, c, &d0);
        ((0..c).map(|i| w[i][i].clone()).product(), w)
    };
    if debug {
        eprintln!("  hnf at {:.1} ms", ms());
    }
    Some((h, smith(&red)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::form::class_number_brute;

    fn squarefree(n: u64) -> bool {
        (2..).take_while(|q| q * q <= n).all(|q| n % (q * q) != 0)
    }

    fn fundamental(d: i64) -> bool {
        let n = (-d) as u64;
        match d.rem_euclid(16) {
            r if r % 4 == 1 => squarefree(n),
            8 | 12 => squarefree(n / 4),
            _ => false,
        }
    }

    #[test]
    fn small_discriminants_against_brute_force() {
        // fundamental discriminants of both kinds (D = 1 mod 4 and D = 4m),
        // including ones with 2-rank > 0
        let mut checked = 0;
        for d in (5..120_000i64).rev().step_by(53).map(|n| -n).filter(|&d| fundamental(d)) {
            let (g, _) = class_group(&BigInt::from(d)).unwrap();
            assert_eq!(g.h, BigInt::from(class_number_brute(d)), "h({})", d);
            checked += 1;
        }
        assert!(checked > 500);
    }

    #[test]
    fn structures_from_pari() {
        // quadclassunit(D).cyc, PARI 2.17.4 (used as an oracle only)
        let known: &[(&str, &[u64])] = &[
            ("-8888", &[26, 2]),
            ("-3192", &[4, 2, 2]),
            ("-57135", &[36, 2, 2]),
            ("-569701508", &[2556, 2, 2]),
            ("-1016021983508", &[48592, 2, 2, 2]),
            ("-67128026883063", &[327924, 2, 2, 2, 2]),
            ("-880045948144631", &[12519736, 2]),
            ("-71546116308277364", &[25376784, 2, 2, 2]),
            ("-718243867543907291096", &[2378498846, 2, 2, 2]),
            ("-4777501438908562889540", &[10946067124, 2]),
            ("-100000000000000000000000000319", &[334649460889307]),
            // h > 2^62: the 128-bit HNF
            ("-1000000000000000000000000000000000000003", &[5044956409536984867]),
        ];
        for &(d, cyc) in known {
            let (g, _) = class_group(&d.parse().unwrap()).unwrap();
            let want: Vec<BigInt> = cyc.iter().map(|&c| BigInt::from(c)).collect();
            assert_eq!(g.cyc, want, "cyc({})", d);
        }
    }
}
