import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
print(repr((a.sum(axis=0), a.mean(), a[a % 3 == 0], a.T @ a)))
np.random.seed(0)
x = np.random.randn(100_000)
print(repr((x.mean(), x.std(), np.percentile(x, [5, 50, 95]))))
A = np.array([[4.0, 1, 2], [1, 3, 0], [2, 0, 5]])
w, v = np.linalg.eigh(A)
print(w)
print(repr((np.linalg.solve(A, [1, 2, 3]), np.linalg.det(A), np.allclose(v @ np.diag(w) @ v.T, A))))
x = np.linspace(0, 1, 50)
y = 3 * x**2 - x + 0.05 * np.sin(40 * x)
p = np.polyfit(x, y, 2)
print(repr((p, np.roots(p))))
