import numpy as np
a = np.arange(12)
print(repr(a.reshape(3, 4)), repr(a.reshape(2, -1)), repr(a.reshape((2, 2, 3))), repr(np.reshape(a, (4, 3)).T))
m = a.reshape(3, 4)
print(repr(m.T), repr(m.transpose()), repr(np.transpose(m.reshape(3, 2, 2), (2, 0, 1)).shape), repr(m.swapaxes(0, 1)))
print(repr(m.ravel()), repr(m.T.ravel()), repr(m.flatten()), repr(np.squeeze(np.zeros((1, 3, 1))).shape), repr(np.expand_dims(a, 0).shape))
print(repr(np.concatenate([m, m], axis=1)), repr(np.concatenate([a, a])), repr(np.stack([a, a], axis=1).shape), repr(np.vstack([a, a]).shape))
print(repr(np.hstack([np.zeros(2), np.ones(3)])), repr(np.column_stack([np.arange(3), np.arange(3)])), repr(np.dstack([m, m]).shape))
print(repr(np.split(a, 3)), repr(np.array_split(a, 5)), repr(np.split(m, [1], axis=1)))
print(repr(np.tile(np.array([1, 2]), 3)), repr(np.tile(np.array([1, 2]), (2, 2))), repr(np.repeat(np.array([1, 2]), 2)), repr(np.repeat(m, 2, axis=0).shape))
print(repr(np.flip(a)), repr(np.fliplr(m)), repr(np.flipud(m)), repr(np.roll(a, 3)), repr(np.roll(m, 1, axis=1)), repr(np.rot90(m)))
print(repr(np.moveaxis(np.zeros((2, 3, 4)), 0, -1).shape), repr(np.atleast_2d(a).shape), repr(np.broadcast_to(np.arange(3), (2, 3))))
print(repr(np.append(a, [99])), repr(np.insert(a, 2, -1)), repr(np.delete(a, [0, 1])), repr(np.pad(np.arange(3), 2)), repr(np.resize(np.arange(3), 7)))
print(repr(np.sort(np.array([[3, 1, 2], [9, 7, 8]]))), repr(np.sort(np.array([[3, 1], [0, 5]]), axis=0)), repr(np.argsort(np.array([0.3, 0.1, 0.2]))))
print(repr(np.unique(np.array([3, 3, 1, 2, 1]), return_counts=True)), repr(np.unique(np.array([[1, 2], [2, 3]]))), repr(np.unique(np.array([2, 1, 2]), return_index=True, return_inverse=True)))
print(repr(np.where(np.array([1, 0, 3]))), repr(np.nonzero(np.array([[0, 1], [2, 0]]))), repr(np.argwhere(np.array([[0, 1], [2, 0]]))), repr(np.flatnonzero(np.array([0, 2, 0, 3]))))
print(repr(np.searchsorted(np.array([1, 3, 5, 7]), [2, 5, 9])), repr(np.searchsorted(np.array([1, 3, 5]), 3, side="right")), repr(np.isin(np.array([1, 2, 3]), [2, 3])))
print(repr(np.diff(np.array([1, 4, 9, 16]), n=2)), repr(np.diff(m, axis=0)), repr(np.gradient(np.array([1.0, 4, 9, 16]))), repr(np.trapezoid(np.array([1.0, 2, 3]))))
print(repr(np.interp(np.array([0.5, 1.5, 5]), np.array([0, 1, 2]), np.array([0, 10, 20]))), repr(np.convolve(np.array([1, 2, 3]), np.array([0, 1, 0.5]))))
print(repr(np.histogram(np.array([1, 2, 2, 3, 3, 3, 4]), bins=3)), repr(np.bincount(np.array([0, 1, 1, 3]))), repr(np.digitize(np.array([0.2, 6.4, 3.0]), np.array([0, 1, 2.5, 4]))))
print(m.shape, len(m), m.size, m.ndim, m.T.shape, m.itemsize, m.nbytes, m.dtype.name, m.strides, m.T.strides)
