import numpy as np
np.random.seed(0)
print(repr(np.random.rand(5)), repr(np.random.rand()), repr(np.random.rand(2, 3)))
print(repr(np.random.randn(6)), repr(np.random.randn()))
print(repr(np.random.randint(0, 10, size=12)), repr(np.random.randint(5)), repr(np.random.randint(-1000, 10**6, 4)))
print(repr(np.random.normal(5, 2, size=4)), repr(np.random.uniform(-1, 1, 3)), repr(np.random.random((2, 2))))
print(repr(np.random.exponential(2.0, 3)), repr(np.random.poisson(3.0, 8)), repr(np.random.poisson(25.0, 8)))
a = np.arange(10); np.random.shuffle(a); print(repr(a))
print(repr(np.random.permutation(8)), repr(np.random.choice(5, 6)), repr(np.random.choice([10, 20, 30], 4, p=[0.1, 0.3, 0.6])))
print(repr(np.random.choice(10, 4, replace=False)), repr(np.random.choice(["a", "b", "c"], 3) if False else 0))
rs = np.random.RandomState(42)
print(repr(rs.rand(3)), repr(rs.randn(3)), repr(rs.randint(0, 100, 5)), repr(rs.normal(size=2)))
np.random.seed(12345)
x = np.random.randn(1000)
print(repr(x.mean()), repr(x.std()), repr(np.sort(x)[:3]))
g = np.random.default_rng(42)
print(repr(g.random(5)), repr(g.integers(0, 10, 8)), repr(g.integers(100)), repr(g.uniform(1, 2, 3)))
print(repr(g.permutation(10)), repr(g.choice(10, 3)), repr(g.choice(10, 4, replace=False)), repr(g.integers(0, 2**40, 3)))
g2 = np.random.default_rng(2024)
print(repr(g2.random()), repr(g2.integers(1, 7, size=(2, 3))))
b = np.arange(6); g2.shuffle(b); print(repr(b))
