# Exact linear algebra over ZZ and QQ (sagebrush.linalg) and long
# polynomial products and gcds (sagebrush.poly), against Sage.
A = matrix(QQ, [[1,2,3],[4,5,6],[7,8,10]])
print(A.det())
print(A.rank())
print(A.inverse())
print(A.charpoly())
print(A.charpoly('t'))
print(~A * A == identity_matrix(QQ, 3))
B = matrix(QQ, [[1,2,3],[4,5,6],[7,8,9]])
print(B.det(), B.rank(), B.pivots())
print(B.echelon_form())
print(B.kernel())
print(B.right_kernel())
print(B.solve_right(vector([1,2,3])))
print(B.solve_left(vector([1,2,3])))
try:
    B.solve_right(vector([1,0,0]))
except ValueError as e:
    print("ValueError:", e)
try:
    B.inverse()
except ZeroDivisionError as e:
    print("ZeroDivisionError:", e)
C = matrix(QQ, [[1/2, 1/3, 1/5], [2/7, 3/11, 5/13], [1, -1, 1/17]])
print(C.det())
print(C.inverse())
print(C.charpoly())
print(C.solve_right(vector([1, 1/2, 1/3])))
print(C.solve_right(matrix(QQ, [[1, 0], [0, 1], [1, 1]])))
Z = matrix(ZZ, [[2,4,6],[1,2,3]])
print(Z.kernel())
print(Z.right_kernel())
print(Z.rank(), Z.det() if Z.is_square() else "not square")
D = matrix(ZZ, 12, 12, [power_mod(i + 2, j + 3, 17) - 8 for i in range(12) for j in range(12)])
print(D.det())
print(D.charpoly())
print(D.rank())
E = matrix(ZZ, 10, 14, [power_mod(i % 5 + 2, j + 1, 11) - 5 for i in range(10) for j in range(14)])
print(E.rank(), E.pivots())
print(E.right_kernel())
print(E.echelon_form() == E.hermite_form())
print(E.change_ring(QQ).echelon_form())
F = matrix(ZZ, 30, 30, [power_mod(i + 2, j + 3, 1009) - 504 for i in range(30) for j in range(30)])
print(F.det())
print(F.inverse()[0][0], F.inverse()[29][29])
x = vector(QQ, [1]*30)
s = F.solve_right(x)
print(F * s == x)
print(s[0])
print(matrix(ZZ,[[1,2],[3,4]]) * vector([1,1]))
print(matrix(ZZ, 0, 3).kernel())
print(matrix(QQ, [[0,0],[0,0]]).kernel())
# long products and gcds of polynomials
R.<x> = ZZ[]
f = sum(((i*i + 1) % 23 - 11) * x^i for i in range(300))
g = sum(((i*7 + 2) % 19 - 9) * x^i for i in range(250))
h = sum(((i*5 + 3) % 13 - 6) * x^i for i in range(120))
print((f*g).degree(), (f*g)[100], (f*g)[400], (f*g).coefficients()[:5])
print((f*h).gcd(g*h) == h * (f.gcd(g)) or (f*h).gcd(g*h) == -h * (f.gcd(g)))
print(((f*h).gcd(g*h)).degree(), ((f*h).gcd(g*h)).leading_coefficient())
print((2*x+2).gcd(4*x+4), (6*x^2-6).gcd(4*x-4), R(0).gcd(R(-3)), (-x).gcd(R(0)))
S.<y> = QQ[]
p = S(f) / 3
q = S(g) * (2/5)
print((p*S(h)).gcd(q*S(h)) == S(h).monic() * S(f).gcd(S(g)))
print((y^2 - 1).gcd(y^2 + 2*y + 1))
