// The 3D viewer for Sagebrush's Graphics3d scenes (lib/sage_plot3d.py):
// plain WebGL 1, no libraries.  Drag to rotate, scroll (once the view has
// focus) or pinch to zoom, double-click or "0" to reset, arrow keys to turn.
//
// One plain script, used twice: the notebook page loads it on demand, and
// lib/_viewer3d.py embeds it in the HTML that Jupyter shows (generated by
// scripts/gen-viewer3d.mjs).  It defines window.SagebrushViewer3d.mount(
// container, scene): the container's fallback SVG is hidden once WebGL works.
(function () {
  "use strict";
  if (typeof window === "undefined" || window.SagebrushViewer3d) return;

  const VS = "attribute vec3 p;attribute vec3 n;attribute vec3 c;uniform mat4 M;uniform mat4 P;uniform float ps;" +
    "varying vec3 vn;varying vec3 vc;varying vec3 vp;" +
    "void main(){vec4 q=M*vec4(p,1.0);vp=q.xyz;vn=(M*vec4(n,0.0)).xyz;vc=c;gl_Position=P*q;gl_PointSize=ps;}";
  const FS = "precision mediump float;varying vec3 vn;varying vec3 vc;varying vec3 vp;uniform float lit;uniform float alpha;uniform float pt;" +
    "void main(){if(pt>0.5){vec2 d=gl_PointCoord-0.5;if(dot(d,d)>0.25)discard;}vec3 col=vc;" +
    "if(lit>0.5){vec3 N=normalize(vn);vec3 V=normalize(-vp);if(dot(N,V)<0.0)N=-N;" +
    "vec3 L=normalize(vec3(-0.4,0.6,1.0));float d=abs(dot(N,L));vec3 H=normalize(L+V);float s=pow(max(dot(N,H),0.0),48.0);" +
    "col=vc*(0.3+0.62*d)+vec3(0.16*s)+0.06*(vec3(1.0)-vc);}gl_FragColor=vec4(col,alpha);}";

  const hex = (h) => [parseInt(h.slice(1, 3), 16) / 255, parseInt(h.slice(3, 5), 16) / 255, parseInt(h.slice(5, 7), 16) / 255];
  const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
  const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  const unit = (a) => { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; };

  function perspective(fovy, aspect, near, far) {
    const f = 1 / Math.tan(fovy / 2), nf = 1 / (near - far);
    return [f / aspect, 0, 0, 0, 0, f, 0, 0, 0, 0, (far + near) * nf, -1, 0, 0, 2 * far * near * nf, 0];
  }
  function lookAt(eye, target, up) {
    const z = unit(sub(eye, target)), x = unit(cross(up, z)), y = cross(z, x);
    return [x[0], y[0], z[0], 0, x[1], y[1], z[1], 0, x[2], y[2], z[2], 0, -dot(x, eye), -dot(y, eye), -dot(z, eye), 1];
  }
  const apply = (m, p) => [m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12], m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13],
    m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14], m[3] * p[0] + m[7] * p[1] + m[11] * p[2] + m[15]];

  function niceTicks(lo, hi, target) {
    if (!(hi > lo)) return { ticks: [lo], step: 1 };
    const raw = (hi - lo) / target, mag = Math.pow(10, Math.floor(Math.log10(raw)));
    let step = mag;
    for (const m of [1, 2, 2.5, 5, 10]) if (m * mag >= raw) { step = m * mag; break; }
    const ticks = [];
    for (let k = Math.ceil(lo / step - 1e-9); k * step <= hi + step * 1e-9; k++) ticks.push(+(k * step).toFixed(12));
    return { ticks, step };
  }
  function tickLabel(v, step) {
    if (v === 0) return "0";
    const a = Math.abs(v);
    if (a >= 1e6 || a < 1e-4) return v.toPrecision(3).replace(/\.?0+e/, "e").replace("e+", "e");
    let d = 0;
    while (d < 12 && Math.abs(step * 10 ** d - Math.round(step * 10 ** d)) > 1e-6 * step * 10 ** d) d++;
    return v.toFixed(d);
  }

  // Geometry in display coordinates d = (p - mid) * scale, inside [-1, 1]^3.
  function build(scene) {
    const mid = [0, 1, 2].map((i) => (scene.lo[i] + scene.hi[i]) / 2), sc = scene.scale;
    const D = (pos, i) => [(pos[i] - mid[0]) * sc[0], (pos[i + 1] - mid[1]) * sc[1], (pos[i + 2] - mid[2]) * sc[2]];
    const tris = [], lines = [], points = [], texts = [];
    for (const o of scene.objects) {
      if (o.type === "mesh") {
        const nv = o.pos.length / 3, P = [], N = new Array(nv).fill(0).map(() => [0, 0, 0]);
        for (let i = 0; i < nv; i++) P.push(D(o.pos, 3 * i));
        for (let t = 0; t < o.idx.length; t += 3) {
          const [a, b, c] = [o.idx[t], o.idx[t + 1], o.idx[t + 2]];
          const n = cross(sub(P[b], P[a]), sub(P[c], P[a]));
          for (const v of [a, b, c]) { N[v][0] += n[0]; N[v][1] += n[1]; N[v][2] += n[2]; }
        }
        const base = hex(o.color);
        const C = (v) => (o.colors ? [o.colors[3 * v] / 255, o.colors[3 * v + 1] / 255, o.colors[3 * v + 2] / 255] : base);
        const pos = [], nor = [], col = [];
        for (let t = 0; t < o.idx.length; t++) {
          const v = o.idx[t];
          pos.push(...P[v]); nor.push(...unit(N[v])); col.push(...C(v));
        }
        tris.push({ pos, nor, col, alpha: o.opacity ?? 1 });
      } else if (o.type === "lines") {
        const c = hex(o.color);
        if ((o.width ?? 1) >= 1.4) tris.push(tubes(o.pos, D, c, 0.0035 * o.width));
        else {
          const pos = [], col = [];
          for (let i = 0; i < o.pos.length; i += 3) { pos.push(...D(o.pos, i)); col.push(...c); }
          lines.push({ pos, col });
        }
      } else if (o.type === "points") {
        const pos = [], col = [], c = hex(o.color);
        for (let i = 0; i < o.pos.length; i += 3) { pos.push(...D(o.pos, i)); col.push(...c); }
        points.push({ pos, col, size: Math.max(2, Math.sqrt(o.size || 6) * 2.4) });
      } else if (o.type === "text") texts.push({ at: D(o.pos, 0), text: o.text, color: o.color });
    }
    return { tris, lines, points, texts };
  }

  // a thick polyline as six-sided tubes (lineWidth > 1 is not portable)
  function tubes(pos, D, c, r) {
    const out = { pos: [], nor: [], col: [], alpha: 1 };
    for (let i = 0; i + 5 < pos.length; i += 6) {
      const a = D(pos, i), b = D(pos, i + 3), t = unit(sub(b, a));
      const q = unit(cross(t, Math.abs(t[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0])), s = cross(t, q);
      const ring = [];
      for (let k = 0; k < 6; k++) {
        const ang = (k * Math.PI) / 3, n = [0, 1, 2].map((j) => Math.cos(ang) * q[j] + Math.sin(ang) * s[j]);
        ring.push(n);
      }
      for (let k = 0; k < 6; k++) {
        const n0 = ring[k], n1 = ring[(k + 1) % 6];
        const A0 = a.map((v, j) => v + r * n0[j]), A1 = a.map((v, j) => v + r * n1[j]);
        const B0 = b.map((v, j) => v + r * n0[j]), B1 = b.map((v, j) => v + r * n1[j]);
        for (const [p, n] of [[A0, n0], [B0, n0], [B1, n1], [A0, n0], [B1, n1], [A1, n1]]) { out.pos.push(...p); out.nor.push(...n); out.col.push(...c); }
      }
    }
    return out;
  }

  function mount(container, scene) {
    if (!container || !scene) return false;
    const fallback = container.querySelector("svg");
    const canvas = document.createElement("canvas");
    const gl = canvas.getContext("webgl", { antialias: true, alpha: true, premultipliedAlpha: false, preserveDrawingBuffer: true });
    if (!gl) return false;
    const prog = program(gl);
    if (!prog) return false;
    const geo = build(scene);
    const buf = (data) => { const b = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, b); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(data), gl.STATIC_DRAW); return b; };
    const draws = [];
    for (const t of geo.tris) draws.push({ mode: gl.TRIANGLES, n: t.pos.length / 3, p: buf(t.pos), nn: buf(t.nor), c: buf(t.col), lit: 1, alpha: t.alpha });
    for (const l of geo.lines) draws.push({ mode: gl.LINES, n: l.pos.length / 3, p: buf(l.pos), nn: null, c: buf(l.col), lit: 0, alpha: 1 });
    for (const q of geo.points) draws.push({ mode: gl.POINTS, n: q.pos.length / 3, p: buf(q.pos), nn: null, c: buf(q.col), lit: 0, alpha: 1, size: q.size });
    // the frame: the box's 12 edges
    const corners = [];
    for (const x of [-1, 1]) for (const y of [-1, 1]) for (const z of [-1, 1]) corners.push([x, y, z]);
    const hx = scene.hi.map((h, i) => (h - scene.lo[i]) * scene.scale[i] / 2);
    const C = (i, j, k) => [(2 * i - 1) * hx[0], (2 * j - 1) * hx[1], (2 * k - 1) * hx[2]];
    const edges = [];
    for (const a of [0, 1]) for (const b of [0, 1]) { edges.push([[0, a, b], [1, a, b], 0], [[a, 0, b], [a, 1, b], 1], [[a, b, 0], [a, b, 1], 2]); }
    const framePos = [];
    for (const [s, t] of edges) framePos.push(...C(...s), ...C(...t));
    const frameBuf = buf(framePos), frameCol = buf(new Array(framePos.length).fill(0.5));

    // layout: the canvas over the hidden SVG, labels as positioned spans
    const wrap = document.createElement("div");
    wrap.className = "sb3d-view";
    wrap.style.cssText = "position:relative;width:100%;touch-action:none;user-select:none";
    canvas.style.cssText = "display:block;width:100%;outline:none;cursor:grab";
    canvas.tabIndex = 0;
    canvas.setAttribute("role", "img");
    canvas.setAttribute("aria-label", (scene.description || "3D plot") + ". Drag to rotate, scroll or pinch to zoom, double-click to reset.");
    canvas.title = "Drag to rotate; click, then scroll to zoom; double-click to reset";
    wrap.appendChild(canvas);
    const layer = document.createElement("div");
    layer.style.cssText = "position:absolute;inset:0;pointer-events:none;font:10px system-ui,-apple-system,Segoe UI,Helvetica,Arial,sans-serif;overflow:hidden";
    wrap.appendChild(layer);
    if (scene.title) {
      const t = document.createElement("div");
      t.textContent = scene.title;
      t.style.cssText = "text-align:center;font-weight:600;font-size:15px;margin:4px 0";
      container.appendChild(t);
    }
    container.appendChild(wrap);
    if (fallback) fallback.style.display = "none";
    const restore = () => { wrap.remove(); if (fallback) fallback.style.display = ""; };
    canvas.addEventListener("webglcontextlost", restore);

    const labels = [];
    const label = (i) => {
      while (labels.length <= i) {
        const s = document.createElement("span");
        s.style.cssText = "position:absolute;white-space:nowrap;transform:translate(-50%,-50%)";
        layer.appendChild(s);
        labels.push(s);
      }
      return labels[i];
    };

    const view0 = { az: scene.azimuth ?? -60, el: scene.elevation ?? 25, zoom: 1 };
    let view = { ...view0 }, W = 0, H = 0, pending = false;
    const ink = () => {
      const m = /rgba?\(([\d.]+),\s*([\d.]+),\s*([\d.]+)/.exec(getComputedStyle(container).color || "");
      return m ? [m[1] / 255, m[2] / 255, m[3] / 255] : [0, 0, 0];
    };

    function draw() {
      pending = false;
      const dpr = window.devicePixelRatio || 1;
      const w = Math.min(container.clientWidth || 560, 640), h = Math.round(w * 0.82);
      if (w !== W || h !== H) {
        W = w; H = h;
        canvas.width = Math.round(w * dpr); canvas.height = Math.round(h * dpr);
        canvas.style.height = h + "px";
      }
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.clearColor(0, 0, 0, 0);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
      gl.enable(gl.DEPTH_TEST);
      const az = (view.az * Math.PI) / 180, el = (view.el * Math.PI) / 180, dist = 5.2 / view.zoom;
      const eye = [dist * Math.cos(el) * Math.cos(az), dist * Math.cos(el) * Math.sin(az), dist * Math.sin(el)];
      const M = lookAt(eye, [0, 0, 0], [0, 0, 1]);
      const P = perspective((30 * Math.PI) / 180, W / H, 0.1, 50);
      gl.useProgram(prog.p);
      gl.uniformMatrix4fv(prog.M, false, new Float32Array(M));
      gl.uniformMatrix4fv(prog.P, false, new Float32Array(P));
      const run = (d) => {
        gl.bindBuffer(gl.ARRAY_BUFFER, d.p);
        gl.vertexAttribPointer(prog.ap, 3, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(prog.ap);
        if (d.nn) { gl.bindBuffer(gl.ARRAY_BUFFER, d.nn); gl.vertexAttribPointer(prog.an, 3, gl.FLOAT, false, 0, 0); gl.enableVertexAttribArray(prog.an); }
        else { gl.disableVertexAttribArray(prog.an); gl.vertexAttrib3f(prog.an, 0, 0, 1); }
        gl.bindBuffer(gl.ARRAY_BUFFER, d.c);
        gl.vertexAttribPointer(prog.ac, 3, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(prog.ac);
        gl.uniform1f(prog.lit, d.lit);
        gl.uniform1f(prog.alpha, d.alpha);
        gl.uniform1f(prog.pt, d.mode === gl.POINTS ? 1 : 0);
        gl.uniform1f(prog.ps, (d.size || 1) * dpr);
        gl.drawArrays(d.mode, 0, d.n);
      };
      gl.disable(gl.BLEND);
      gl.depthMask(true);
      for (const d of draws) if (d.alpha >= 1) run(d);
      if (scene.frame !== false) {
        const c = ink(), col = [];
        for (let i = 0; i < framePos.length / 3; i++) col.push(...c);
        gl.bindBuffer(gl.ARRAY_BUFFER, frameCol);
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(col), gl.DYNAMIC_DRAW);
        gl.enable(gl.BLEND);
        gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
        run({ mode: gl.LINES, n: framePos.length / 3, p: frameBuf, nn: null, c: frameCol, lit: 0, alpha: 0.45 });
      }
      gl.enable(gl.BLEND);
      gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
      gl.depthMask(false);
      for (const d of draws) if (d.alpha < 1) run(d);
      gl.depthMask(true);
      placeLabels(M, P);
    }

    // screen position (CSS pixels) of a display point
    const screen = (M, P, p) => {
      const q = apply(P, apply(M, p));
      return [(q[0] / q[3] + 1) * W / 2, (1 - q[1] / q[3]) * H / 2, q[2] / q[3]];
    };

    function placeLabels(M, P) {
      let n = 0;
      const put = (x, y, text, style) => {
        const s = label(n++);
        s.style.left = x + "px"; s.style.top = y + "px"; s.style.display = "";
        s.textContent = text;
        s.style.fontStyle = style?.italic ? "italic" : "";
        s.style.fontSize = style?.size ? style.size + "px" : "";
        s.style.color = style?.color || "";
      };
      for (const t of geo.texts) { const p = screen(M, P, t.at); put(p[0], p[1], t.text, { size: 12, color: t.color }); }
      if (scene.frame !== false) {
        const pts = {};
        for (const i of [0, 1]) for (const j of [0, 1]) for (const k of [0, 1]) pts[[i, j, k]] = screen(M, P, C(i, j, k));
        const all = Object.values(pts), cx = all.reduce((s, p) => s + p[0], 0) / 8, cy = all.reduce((s, p) => s + p[1], 0) / 8;
        for (let axis = 0; axis < 3; axis++) {
          let best = null, score = -Infinity;
          for (const [s, t, ax] of edges) {
            if (ax !== axis) continue;
            const a = pts[s], b = pts[t], m = [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
            const sc = (axis !== 2 ? m[1] - cy : cx - m[0]) - 40 * ((a[2] + b[2]) / 2);
            if (sc > score) { score = sc; best = [a, b]; }
          }
          const [a, b] = best, lo = scene.lo[axis], hi = scene.hi[axis];
          const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2, dl = Math.hypot(mx - cx, my - cy) || 1;
          const ox = (mx - cx) / dl, oy = (my - cy) / dl;
          const { ticks, step } = niceTicks(lo, hi, 4);
          for (const v of ticks) {
            if (v < lo - 1e-9 * (hi - lo) || v > hi + 1e-9 * (hi - lo)) continue;
            const f = hi > lo ? (v - lo) / (hi - lo) : 0.5;
            put(a[0] + (b[0] - a[0]) * f + 14 * ox, a[1] + (b[1] - a[1]) * f + 12 * oy, tickLabel(v, step));
          }
          const name = (scene.labels || [])[axis];
          if (name) put(mx + 34 * ox, my + 30 * oy, name.replace(/^\$(.*)\$$/, "$1"), { italic: true, size: 12 });
        }
      }
      for (let i = n; i < labels.length; i++) labels[i].style.display = "none";
    }

    const redraw = () => { if (!pending) { pending = true; requestAnimationFrame(() => { if (canvas.isConnected) draw(); }); } };
    // interaction: pointers (one rotates, two pinch), wheel, keys
    const ptrs = new Map();
    let pinch = null;
    canvas.addEventListener("pointerdown", (e) => {
      canvas.setPointerCapture(e.pointerId);
      ptrs.set(e.pointerId, [e.clientX, e.clientY]);
      canvas.style.cursor = "grabbing";
      if (ptrs.size === 2) { const [p, q] = [...ptrs.values()]; pinch = { d: Math.hypot(p[0] - q[0], p[1] - q[1]), zoom: view.zoom }; }
    });
    canvas.addEventListener("pointermove", (e) => {
      const last = ptrs.get(e.pointerId);
      if (!last) return;
      const now = [e.clientX, e.clientY];
      ptrs.set(e.pointerId, now);
      if (ptrs.size === 2 && pinch) {
        const [p, q] = [...ptrs.values()];
        view.zoom = Math.min(8, Math.max(0.3, (pinch.zoom * Math.hypot(p[0] - q[0], p[1] - q[1])) / (pinch.d || 1)));
      } else if (ptrs.size === 1) {
        view.az -= (now[0] - last[0]) * 0.5;
        view.el = Math.max(-89, Math.min(89, view.el + (now[1] - last[1]) * 0.5));
      }
      redraw();
    });
    const up = (e) => { ptrs.delete(e.pointerId); if (ptrs.size < 2) pinch = null; if (!ptrs.size) canvas.style.cursor = "grab"; };
    canvas.addEventListener("pointerup", up);
    canvas.addEventListener("pointercancel", up);
    canvas.addEventListener("wheel", (e) => {
      if (document.activeElement !== canvas && !e.ctrlKey) return; // let the page scroll
      e.preventDefault();
      view.zoom = Math.min(8, Math.max(0.3, view.zoom * Math.exp(-e.deltaY * 0.0015)));
      redraw();
    }, { passive: false });
    canvas.addEventListener("dblclick", () => { view = { ...view0 }; redraw(); });
    canvas.addEventListener("keydown", (e) => {
      const k = e.key;
      if (k === "ArrowLeft") view.az += 5; else if (k === "ArrowRight") view.az -= 5;
      else if (k === "ArrowUp") view.el = Math.min(89, view.el + 5); else if (k === "ArrowDown") view.el = Math.max(-89, view.el - 5);
      else if (k === "+" || k === "=") view.zoom = Math.min(8, view.zoom * 1.15); else if (k === "-") view.zoom = Math.max(0.3, view.zoom / 1.15);
      else if (k === "0") view = { ...view0 };
      else return;
      e.preventDefault();
      redraw();
    });
    if (typeof ResizeObserver !== "undefined") new ResizeObserver(redraw).observe(container);
    if (typeof matchMedia !== "undefined") matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change", redraw);
    new MutationObserver(redraw).observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme", "class"] });
    draw();
    return true;
  }

  function program(gl) {
    const sh = (type, src) => { const s = gl.createShader(type); gl.shaderSource(s, src); gl.compileShader(s); return gl.getShaderParameter(s, gl.COMPILE_STATUS) ? s : null; };
    const v = sh(gl.VERTEX_SHADER, VS), f = sh(gl.FRAGMENT_SHADER, FS);
    if (!v || !f) return null;
    const p = gl.createProgram();
    gl.attachShader(p, v); gl.attachShader(p, f); gl.linkProgram(p);
    if (!gl.getProgramParameter(p, gl.LINK_STATUS)) return null;
    const u = (n) => gl.getUniformLocation(p, n);
    return { p, ap: gl.getAttribLocation(p, "p"), an: gl.getAttribLocation(p, "n"), ac: gl.getAttribLocation(p, "c"),
      M: u("M"), P: u("P"), ps: u("ps"), lit: u("lit"), alpha: u("alpha"), pt: u("pt") };
  }

  window.SagebrushViewer3d = { mount };
})();
