// The 3D viewer for Sagebrush's scenes: Graphics3d (lib/sage_plot3d.py)
// and k3d plots (lib/k3d).  Plain WebGL, no libraries: WebGL2 when there
// is one (needed for volume rendering), else WebGL1.  Drag to rotate,
// scroll (once the view has focus) or pinch to zoom, double-click or "0"
// to reset, arrow keys to turn.
//
// Scenes of version 2 (k3d) carry their arrays in binary (base64 of
// little-endian float32/uint32/uint8): meshes of millions of triangles
// are drawn indexed, colored through their color map per vertex; volumes
// are ray-marched through a 3D texture.
//
// One plain script, used twice: the notebook page loads it on demand, and
// lib/_viewer3d.py embeds it in the HTML that Jupyter shows and that
// get_snapshot() saves (generated by scripts/gen-viewer3d.mjs).  It
// defines window.SagebrushViewer3d.mount(container, scene): the
// container's fallback SVG is hidden once WebGL works.
(function () {
  "use strict";
  if (typeof window === "undefined" || window.SagebrushViewer3d) return;

  // The main program: lit triangles (smooth, or flat from screen-space
  // derivatives), unlit lines, and points (discs, or shaded as spheres).
  const VS = "attribute vec3 p;attribute vec3 n;attribute vec3 c;uniform mat4 M;uniform mat4 P;uniform float ps;uniform float psScale;" +
    "varying vec3 vn;varying vec3 vc;varying vec3 vp;" +
    "void main(){vec4 q=M*vec4(p,1.0);vp=q.xyz;vn=(M*vec4(n,0.0)).xyz;vc=c;gl_Position=P*q;" +
    "gl_PointSize=psScale>0.0?max(1.0,ps*psScale/max(-q.z,0.01)):ps;}";
  const FS = "varying vec3 vn;varying vec3 vc;varying vec3 vp;uniform float lit;uniform float alpha;uniform float pt;uniform float flatN;" +
    "void main(){vec3 col=vc;" +
    "if(pt>0.5){vec2 d=gl_PointCoord-0.5;float r2=dot(d,d);if(r2>0.25)discard;" +
    "if(pt>1.5){float z=sqrt(max(0.25-r2,0.0))*2.0;col=vc*(0.35+0.65*z)+vec3(0.25*pow(z,24.0));}}" +
    "if(lit>0.5){vec3 N=normalize(vn);\n#if FLATOK\nif(flatN>0.5)N=normalize(cross(dFdx(vp),dFdy(vp)));\n#endif\n" +
    "vec3 V=normalize(-vp);if(dot(N,V)<0.0)N=-N;" +
    "vec3 L=normalize(vec3(-0.4,0.6,1.0));float d=abs(dot(N,L));vec3 H=normalize(L+V);float s=pow(max(dot(N,H),0.0),48.0);" +
    "col=vc*(0.3+0.62*d)+vec3(0.16*s)+0.06*(vec3(1.0)-vc);}gl_FragColor=vec4(col,alpha);}";

  // Volume rendering (WebGL2): the box's back faces start rays from the
  // eye; front-to-back compositing of the color map and opacity function.
  const VOL_VS = "#version 300 es\nin vec3 p;uniform mat4 M;uniform mat4 P;out vec3 wp;void main(){wp=p;gl_Position=P*M*vec4(p,1.0);}";
  const VOL_FS = "#version 300 es\nprecision highp float;precision highp sampler3D;in vec3 wp;out vec4 o;" +
    "uniform sampler3D vol;uniform sampler2D lut;uniform vec3 eye;uniform vec3 bmin;uniform vec3 bmax;uniform float samples;uniform float alphaCoef;" +
    "void main(){vec3 dir=normalize(wp-eye);vec3 inv=1.0/dir;vec3 t0=(bmin-eye)*inv;vec3 t1=(bmax-eye)*inv;" +
    "vec3 a=min(t0,t1);vec3 b=max(t0,t1);float tn=max(max(max(a.x,a.y),a.z),0.0);float tf=min(min(b.x,b.y),b.z);" +
    "if(tf<=tn)discard;float dt=length(bmax-bmin)/samples;vec4 acc=vec4(0.0);float k=alphaCoef/samples;" +
    "for(int i=0;i<4096;i++){float t=tn+(float(i)+0.5)*dt;if(t>tf)break;vec3 uvw=(eye+dir*t-bmin)/(bmax-bmin);" +
    "float v=texture(vol,uvw).r;vec4 s=texture(lut,vec2(v,0.5));float al=clamp(s.a*k,0.0,1.0);" +
    "acc.rgb+=(1.0-acc.a)*al*s.rgb;acc.a+=(1.0-acc.a)*al;if(acc.a>0.995)break;}o=acc;}";

  const hex = (h) => [parseInt(h.slice(1, 3), 16) / 255, parseInt(h.slice(3, 5), 16) / 255, parseInt(h.slice(5, 7), 16) / 255];
  const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
  const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  const unit = (a) => { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; };

  function perspective(fovy, aspect, near, far) {
    const f = 1 / Math.tan(fovy / 2), nf = 1 / (near - far);
    return [f / aspect, 0, 0, 0, 0, f, 0, 0, 0, 0, (far + near) * nf, -1, 0, 0, 2 * far * near * nf, 0];
  }
  function lookAt(eye, target, up) {
    const z = unit(sub(eye, target)), x = unit(cross(up, z)), y = cross(z, x);
    return [x[0], y[0], z[0], 0, x[1], y[1], z[1], 0, x[2], y[2], z[2], 0, -dot(x, eye), -dot(y, eye), -dot(z, eye), 1];
  }
  const apply = (m, p) => [m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12], m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13],
    m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14], m[3] * p[0] + m[7] * p[1] + m[11] * p[2] + m[15]];

  function niceTicks(lo, hi, target) {
    if (!(hi > lo)) return { ticks: [lo], step: 1 };
    const raw = (hi - lo) / target, mag = Math.pow(10, Math.floor(Math.log10(raw)));
    let step = mag;
    for (const m of [1, 2, 2.5, 5, 10]) if (m * mag >= raw) { step = m * mag; break; }
    const ticks = [];
    for (let k = Math.ceil(lo / step - 1e-9); k * step <= hi + step * 1e-9; k++) ticks.push(+(k * step).toFixed(12));
    return { ticks, step };
  }
  function tickLabel(v, step) {
    if (v === 0) return "0";
    const a = Math.abs(v);
    if (a >= 1e6 || a < 1e-4) return v.toPrecision(3).replace(/\.?0+e/, "e").replace("e+", "e");
    let d = 0;
    while (d < 12 && Math.abs(step * 10 ** d - Math.round(step * 10 ** d)) > 1e-6 * step * 10 ** d) d++;
    return v.toFixed(d);
  }
  // k3d's axis labels are LaTeX-like: x^+ -> x⁺
  const SUP = { "+": "⁺", "-": "⁻", "0": "⁰", "1": "¹", "2": "²", "3": "³", "4": "⁴", "5": "⁵", "6": "⁶", "7": "⁷", "8": "⁸", "9": "⁹" };
  const axisLabel = (s) => s.replace(/^\$(.*)\$$/, "$1").replace(/\^\{?([+\-0-9]+)\}?/g, (_, t) => [...t].map((c) => SUP[c] ?? c).join(""));

  // ------------------------------------------------------------------ data

  function b64(s) {
    const bin = atob(s), n = bin.length, u = new Uint8Array(n);
    for (let i = 0; i < n; i++) u[i] = bin.charCodeAt(i);
    return u;
  }
  const f32 = (s) => new Float32Array(b64(s).buffer);
  const u32 = (s) => new Uint32Array(b64(s).buffer);

  // a color map [t, r, g, b, ...] as a 256-entry table (RGB floats)
  function cmapTable(cm) {
    const out = new Float32Array(256 * 3);
    const n = cm.length / 4;
    for (let i = 0; i < 256; i++) {
      const t = i / 255;
      let k = 0;
      while (k < n - 2 && cm[4 * (k + 1)] < t) k++;
      const t0 = cm[4 * k], t1 = cm[4 * (k + 1)], f = t1 > t0 ? Math.min(1, Math.max(0, (t - t0) / (t1 - t0))) : 0;
      for (let j = 0; j < 3; j++) out[3 * i + j] = cm[4 * k + 1 + j] + (cm[4 * (k + 1) + 1 + j] - cm[4 * k + 1 + j]) * f;
    }
    return out;
  }
  // per-vertex colors: an attribute through a color map, 0xRRGGBB colors, or one color
  function vertexColors(o, n) {
    const col = new Float32Array(3 * n);
    if (o.attribute && o.color_map) {
      const a = f32(o.attribute), tab = cmapTable(o.color_map), [lo, hi] = o.color_range, s = hi > lo ? 255 / (hi - lo) : 0;
      for (let i = 0; i < n; i++) {
        const k = Math.max(0, Math.min(255, Math.round((a[i] - lo) * s))) * 3;
        col[3 * i] = tab[k]; col[3 * i + 1] = tab[k + 1]; col[3 * i + 2] = tab[k + 2];
      }
    } else if (o.colors) {
      const c = u32(o.colors);
      for (let i = 0; i < n; i++) {
        const v = c[Math.min(i, c.length - 1)];
        col[3 * i] = ((v >> 16) & 255) / 255; col[3 * i + 1] = ((v >> 8) & 255) / 255; col[3 * i + 2] = (v & 255) / 255;
      }
    } else {
      const c = hex(o.color || "#0000ff");
      for (let i = 0; i < n; i++) { col[3 * i] = c[0]; col[3 * i + 1] = c[1]; col[3 * i + 2] = c[2]; }
    }
    return col;
  }

  // Geometry in display coordinates d = (p - mid) * scale, inside [-1, 1]^3.
  function build(scene) {
    const mid = [0, 1, 2].map((i) => (scene.lo[i] + scene.hi[i]) / 2), sc = scene.scale;
    const D = (pos, i) => [(pos[i] - mid[0]) * sc[0], (pos[i + 1] - mid[1]) * sc[1], (pos[i + 2] - mid[2]) * sc[2]];
    const toDisplay = (p) => {
      const out = new Float32Array(p.length);
      for (let i = 0; i < p.length; i += 3) {
        out[i] = (p[i] - mid[0]) * sc[0]; out[i + 1] = (p[i + 1] - mid[1]) * sc[1]; out[i + 2] = (p[i + 2] - mid[2]) * sc[2];
      }
      return out;
    };
    const tris = [], lines = [], points = [], texts = [], meshes = [], volumes = [], texts2d = [];
    for (const o of scene.objects) {
      if (o.type === "mesh") {
        const nv = o.pos.length / 3, P = [], N = new Array(nv).fill(0).map(() => [0, 0, 0]);
        for (let i = 0; i < nv; i++) P.push(D(o.pos, 3 * i));
        for (let t = 0; t < o.idx.length; t += 3) {
          const [a, b, c] = [o.idx[t], o.idx[t + 1], o.idx[t + 2]];
          const n = cross(sub(P[b], P[a]), sub(P[c], P[a]));
          for (const v of [a, b, c]) { N[v][0] += n[0]; N[v][1] += n[1]; N[v][2] += n[2]; }
        }
        // flat (polyhedra): each triangle gets its own normal
        const F = (t) => unit(cross(sub(P[o.idx[t - t % 3 + 1]], P[o.idx[t - t % 3]]), sub(P[o.idx[t - t % 3 + 2]], P[o.idx[t - t % 3]])));
        const base = hex(o.color);
        const C = (v) => (o.colors ? [o.colors[3 * v] / 255, o.colors[3 * v + 1] / 255, o.colors[3 * v + 2] / 255] : base);
        const pos = [], nor = [], col = [];
        for (let t = 0; t < o.idx.length; t++) {
          const v = o.idx[t];
          pos.push(...P[v]); nor.push(...(o.flat ? F(t) : unit(N[v]))); col.push(...C(v));
        }
        tris.push({ pos, nor, col, alpha: o.opacity ?? 1 });
      } else if (o.type === "lines") {
        const c = hex(o.color);
        if ((o.width ?? 1) >= 1.4) tris.push(tubes(o.pos, D, () => c, 0.0035 * o.width));
        else {
          const pos = [], col = [];
          for (let i = 0; i < o.pos.length; i += 3) { pos.push(...D(o.pos, i)); col.push(...c); }
          lines.push({ pos, col });
        }
      } else if (o.type === "points") {
        const pos = [], col = [], c = hex(o.color);
        for (let i = 0; i < o.pos.length; i += 3) { pos.push(...D(o.pos, i)); col.push(...c); }
        points.push({ pos, col, size: Math.max(2, Math.sqrt(o.size || 6) * 2.4) });
      } else if (o.type === "text") texts.push({ at: D(o.pos, 0), text: o.text, color: o.color });
      // ---- version 2 (k3d): binary arrays
      else if (o.type === "mesh2") {
        const pos = toDisplay(f32(o.positions)), idx = u32(o.indices), n = pos.length / 3;
        const col = vertexColors(o, n);
        let nor = null;
        if (!o.flat_shading) {
          nor = new Float32Array(3 * n);
          for (let t = 0; t + 2 < idx.length; t += 3) {
            const a = 3 * idx[t], b = 3 * idx[t + 1], c = 3 * idx[t + 2];
            const ux = pos[b] - pos[a], uy = pos[b + 1] - pos[a + 1], uz = pos[b + 2] - pos[a + 2];
            const vx = pos[c] - pos[a], vy = pos[c + 1] - pos[a + 1], vz = pos[c + 2] - pos[a + 2];
            const nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
            for (const v of [a, b, c]) { nor[v] += nx; nor[v + 1] += ny; nor[v + 2] += nz; }
          }
        }
        meshes.push({ pos, idx, col, nor, alpha: o.opacity ?? 1, side: o.side || "front", flat: !!o.flat_shading, wire: !!o.wireframe });
      } else if (o.type === "points2") {
        const pos = toDisplay(f32(o.positions)), n = pos.length / 3;
        points.push({ pos, col: vertexColors(o, n), worldSize: (o.size || 1) * sc[0], shader: o.shader, alpha: o.opacity ?? 1 });
      } else if (o.type === "line2") {
        const pos = toDisplay(f32(o.positions)), seg = u32(o.segments), n = pos.length / 3;
        const col = vertexColors(o, n);
        const r = (o.width || 0.01) * sc[0] / 2;
        if (o.shader !== "simple" && seg.length / 2 <= 40000 && r * 400 > 1) {
          const at = (i) => [pos[3 * i], pos[3 * i + 1], pos[3 * i + 2]];
          const flat = [];
          for (let k = 0; k + 1 < seg.length; k += 2) flat.push(...at(seg[k]), ...at(seg[k + 1]));
          const cols = (k) => { const i = seg[k]; return [col[3 * i], col[3 * i + 1], col[3 * i + 2]]; };
          tris.push(tubes(flat, (p, i) => [p[i], p[i + 1], p[i + 2]], (k) => cols(2 * k), r, o.opacity ?? 1));
        } else {
          const lp = new Float32Array(seg.length * 3), lc = new Float32Array(seg.length * 3);
          for (let k = 0; k < seg.length; k++) {
            const i = seg[k];
            lp.set(pos.subarray(3 * i, 3 * i + 3), 3 * k);
            lc.set(col.subarray(3 * i, 3 * i + 3), 3 * k);
          }
          lines.push({ pos: lp, col: lc });
        }
      } else if (o.type === "volume") {
        const b = o.bounds;
        volumes.push({ data: b64(o.data), shape: o.shape, bmin: D([b[0], b[2], b[4]], 0), bmax: D([b[1], b[3], b[5]], 0), o });
      } else if (o.type === "text2") {
        if (o.mode === "2d") texts2d.push(o);
        else texts.push({ at: D(o.position, 0), text: o.text, color: o.color, size: 12 * (o.size || 1) });
      }
    }
    return { tris, lines, points, texts, meshes, volumes, texts2d };
  }

  // a thick polyline as six-sided tubes (lineWidth > 1 is not portable);
  // color(k) for segment k
  function tubes(pos, D, color, r, alpha = 1) {
    const out = { pos: [], nor: [], col: [], alpha };
    for (let i = 0, k = 0; i + 5 < pos.length; i += 6, k++) {
      const a = D(pos, i), b = D(pos, i + 3), t = unit(sub(b, a));
      const q = unit(cross(t, Math.abs(t[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0])), s = cross(t, q);
      const c = color(k);
      const ring = [];
      for (let j = 0; j < 6; j++) {
        const ang = (j * Math.PI) / 3;
        ring.push([0, 1, 2].map((m) => Math.cos(ang) * q[m] + Math.sin(ang) * s[m]));
      }
      for (let j = 0; j < 6; j++) {
        const n0 = ring[j], n1 = ring[(j + 1) % 6];
        const A0 = a.map((v, m) => v + r * n0[m]), A1 = a.map((v, m) => v + r * n1[m]);
        const B0 = b.map((v, m) => v + r * n0[m]), B1 = b.map((v, m) => v + r * n1[m]);
        for (const [p, n] of [[A0, n0], [B0, n0], [B1, n1], [A0, n0], [B1, n1], [A1, n1]]) { out.pos.push(...p); out.nor.push(...n); out.col.push(...c); }
      }
    }
    return out;
  }

  // a color map and an opacity function as a 256x1 RGBA texture
  function lutData(cm, of) {
    const tab = cmapTable(cm), out = new Uint8Array(256 * 4), m = of.length / 2;
    for (let i = 0; i < 256; i++) {
      const t = i / 255;
      let k = 0;
      while (k < m - 2 && of[2 * (k + 1)] < t) k++;
      const t0 = of[2 * k], t1 = of[2 * (k + 1)] ?? t0, f = t1 > t0 ? Math.min(1, Math.max(0, (t - t0) / (t1 - t0))) : 0;
      const a = m > 1 ? of[2 * k + 1] + ((of[2 * (k + 1) + 1] ?? of[2 * k + 1]) - of[2 * k + 1]) * f : of[1];
      out[4 * i] = Math.round(tab[3 * i] * 255); out[4 * i + 1] = Math.round(tab[3 * i + 1] * 255); out[4 * i + 2] = Math.round(tab[3 * i + 2] * 255);
      out[4 * i + 3] = Math.round(Math.max(0, Math.min(1, a)) * 255);
    }
    return out;
  }

  function mount(container, scene) {
    if (!container || !scene) return false;
    const fallback = container.querySelector("svg");
    const canvas = document.createElement("canvas");
    const opts = { antialias: true, alpha: true, premultipliedAlpha: false, preserveDrawingBuffer: true };
    let gl = canvas.getContext("webgl2", opts);
    const gl2 = !!gl;
    if (!gl) gl = canvas.getContext("webgl", opts);
    if (!gl) return false;
    const uintIdx = gl2 || !!gl.getExtension("OES_element_index_uint");
    const deriv = gl2 || !!gl.getExtension("OES_standard_derivatives");
    const prog = program(gl, gl2, deriv);
    if (!prog) return false;
    const geo = build(scene);
    const buf = (data, target = gl.ARRAY_BUFFER) => {
      const b = gl.createBuffer();
      gl.bindBuffer(target, b);
      gl.bufferData(target, data instanceof Float32Array || data instanceof Uint32Array || data instanceof Uint16Array ? data : new Float32Array(data), gl.STATIC_DRAW);
      return b;
    };
    const draws = [];
    for (const t of geo.tris) draws.push({ mode: gl.TRIANGLES, n: t.pos.length / 3, p: buf(t.pos), nn: buf(t.nor), c: buf(t.col), lit: 1, alpha: t.alpha });
    for (const l of geo.lines) draws.push({ mode: gl.LINES, n: l.pos.length / 3, p: buf(l.pos), nn: null, c: buf(l.col), lit: 0, alpha: 1 });
    for (const q of geo.points) {
      draws.push({ mode: gl.POINTS, n: q.pos.length / 3, p: buf(q.pos), nn: null, c: buf(q.col), lit: 0, alpha: q.alpha ?? 1,
        size: q.size, world: q.worldSize, pt: q.shader && q.shader !== "flat" && q.shader !== "dot" ? 2 : 1 });
    }
    for (const m of geo.meshes) {
      let idx = m.idx;
      if (!uintIdx) {
        if (m.pos.length / 3 > 65535) continue; // (WebGL1 without 32-bit indices)
        idx = Uint16Array.from(idx);
      }
      const d = { mode: gl.TRIANGLES, n: idx.length, p: buf(m.pos), nn: m.nor ? buf(m.nor) : null, c: buf(m.col), lit: 1, alpha: m.alpha,
        ib: buf(idx, gl.ELEMENT_ARRAY_BUFFER), itype: idx instanceof Uint32Array ? gl.UNSIGNED_INT : gl.UNSIGNED_SHORT, flat: m.flat, side: m.side };
      draws.push(d);
      if (m.wire) {
        const e = new (idx instanceof Uint32Array ? Uint32Array : Uint16Array)(idx.length * 2);
        for (let t = 0; t + 2 < idx.length; t += 3) e.set([idx[t], idx[t + 1], idx[t + 1], idx[t + 2], idx[t + 2], idx[t]], 2 * t);
        draws.push({ ...d, mode: gl.LINES, n: e.length, ib: buf(e, gl.ELEMENT_ARRAY_BUFFER), lit: 0, flat: false });
      }
    }
    const vols = [];
    if (gl2 && geo.volumes.length) {
      const vp = volumeProgram(gl);
      for (const v of geo.volumes) {
        if (!vp) break;
        const [nz, ny, nx] = v.shape;
        const tex = gl.createTexture();
        gl.activeTexture(gl.TEXTURE0);
        gl.bindTexture(gl.TEXTURE_3D, tex);
        gl.pixelStorei(gl.UNPACK_ALIGNMENT, 1);
        gl.texImage3D(gl.TEXTURE_3D, 0, gl.R8, nx, ny, nz, 0, gl.RED, gl.UNSIGNED_BYTE, v.data);
        const filt = v.o.interpolation === false ? gl.NEAREST : gl.LINEAR;
        gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MIN_FILTER, filt);
        gl.texParameteri(gl.TEXTURE_3D, gl.TEXTURE_MAG_FILTER, filt);
        for (const w of [gl.TEXTURE_WRAP_S, gl.TEXTURE_WRAP_T, gl.TEXTURE_WRAP_R]) gl.texParameteri(gl.TEXTURE_3D, w, gl.CLAMP_TO_EDGE);
        const lut = gl.createTexture();
        gl.bindTexture(gl.TEXTURE_2D, lut);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 256, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, lutData(v.o.color_map, v.o.opacity_function));
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        // the box: 12 triangles
        const [x0, y0, z0] = v.bmin, [x1, y1, z1] = v.bmax;
        const c = [[x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0], [x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1]];
        const faces = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [2, 3, 7], [2, 7, 6], [1, 2, 6], [1, 6, 5], [0, 4, 7], [0, 7, 3]];
        const box = [];
        for (const f of faces) for (const i of f) box.push(...c[i]);
        vols.push({ vp, tex, lut, box: buf(box), bmin: v.bmin, bmax: v.bmax, samples: v.o.samples || 512, alphaCoef: v.o.alpha_coef ?? 50 });
      }
    }
    // the frame: the box's 12 edges
    const hx = scene.hi.map((h, i) => (h - scene.lo[i]) * scene.scale[i] / 2);
    const C = (i, j, k) => [(2 * i - 1) * hx[0], (2 * j - 1) * hx[1], (2 * k - 1) * hx[2]];
    const edges = [];
    for (const a of [0, 1]) for (const b of [0, 1]) { edges.push([[0, a, b], [1, a, b], 0], [[a, 0, b], [a, 1, b], 1], [[a, b, 0], [a, b, 1], 2]); }
    const framePos = [];
    for (const [s, t] of edges) framePos.push(...C(...s), ...C(...t));
    const frameBuf = buf(framePos), frameCol = buf(new Array(framePos.length).fill(0.5));

    // layout: the canvas over the hidden SVG, labels as positioned spans
    const wrap = document.createElement("div");
    wrap.className = "sb3d-view";
    wrap.style.cssText = "position:relative;width:100%;touch-action:none;user-select:none";
    canvas.style.cssText = "display:block;width:100%;outline:none;cursor:grab";
    canvas.tabIndex = 0;
    canvas.setAttribute("role", "img");
    canvas.setAttribute("aria-label", (scene.description || "3D plot") +
      ". Drag to rotate, right-drag to pan, scroll or pinch to zoom, double-click to focus on a point; W A S D move; F flies.");
    canvas.title = "Drag: rotate · right-drag: pan · click, then scroll: zoom · double-click: focus · WASD: move · F: fly";
    wrap.appendChild(canvas);
    const layer = document.createElement("div");
    layer.style.cssText = "position:absolute;inset:0;pointer-events:none;font:10px system-ui,-apple-system,Segoe UI,Helvetica,Arial,sans-serif;overflow:hidden";
    wrap.appendChild(layer);
    if (scene.title) {
      const t = document.createElement("div");
      t.textContent = scene.title;
      t.style.cssText = "text-align:center;font-weight:600;font-size:15px;margin:4px 0";
      container.appendChild(t);
    }
    // a colorbar for the (first) color-mapped object
    if (scene.colorbar && scene.colorbar.color_map) {
      const cb = scene.colorbar, cm = cb.color_map, stops = [];
      for (let i = 0; i < cm.length; i += 4) stops.push(`rgb(${Math.round(cm[i + 1] * 255)},${Math.round(cm[i + 2] * 255)},${Math.round(cm[i + 3] * 255)}) ${(cm[i] * 100).toFixed(1)}%`);
      const bar = document.createElement("div");
      bar.style.cssText = "position:absolute;right:10px;top:12px;bottom:40px;width:12px;border:1px solid rgba(128,128,128,.6);" +
        `background:linear-gradient(to top,${stops.join(",")})`;
      const hiL = document.createElement("span"), loL = document.createElement("span");
      hiL.textContent = tickLabel(cb.range[1], Math.abs(cb.range[1] - cb.range[0]) / 10 || 1);
      loL.textContent = tickLabel(cb.range[0], Math.abs(cb.range[1] - cb.range[0]) / 10 || 1);
      hiL.style.cssText = "position:absolute;right:26px;top:6px";
      loL.style.cssText = "position:absolute;right:26px;bottom:34px";
      layer.append(bar, hiL, loL);
    }
    for (const t of geo.texts2d) {
      const s = document.createElement("span");
      s.textContent = t.text;
      s.style.cssText = `position:absolute;left:${(t.position[0] * 100).toFixed(2)}%;top:${(t.position[1] * 100).toFixed(2)}%;font-size:${12 * (t.size || 1)}px;color:${t.color || "inherit"}`;
      layer.appendChild(s);
    }
    container.appendChild(wrap);
    if (fallback) fallback.style.display = "none";
    const restore = () => { wrap.remove(); if (fallback) fallback.style.display = ""; };
    canvas.addEventListener("webglcontextlost", restore);

    const labels = [];
    const label = (i) => {
      while (labels.length <= i) {
        const s = document.createElement("span");
        s.style.cssText = "position:absolute;white-space:nowrap;transform:translate(-50%,-50%)";
        layer.appendChild(s);
        labels.push(s);
      }
      return labels[i];
    };

    // The camera looks at the target t from the direction (az, el) at the
    // distance 5.2 / zoom; z is up.  Orbiting turns about t, looking (fly
    // mode) turns about the eye, and moving shifts both.
    const view0 = { az: scene.azimuth ?? -60, el: scene.elevation ?? 25, zoom: 1, t: [0, 0, 0] };
    let view = { ...view0 }, W = 0, H = 0;
    const ink = () => {
      const m = /rgba?\(([\d.]+),\s*([\d.]+),\s*([\d.]+)/.exec(getComputedStyle(container).color || "");
      return m ? [m[1] / 255, m[2] / 255, m[3] / 255] : [0, 0, 0];
    };
    const fov = (30 * Math.PI) / 180, ZMIN = 0.3, ZMAX = 40;
    const dirOf = (az, el) => {
      const a = (az * Math.PI) / 180, e = (el * Math.PI) / 180;
      return [Math.cos(e) * Math.cos(a), Math.cos(e) * Math.sin(a), Math.sin(e)];
    };
    function camera(v = view) {
      const dist = 5.2 / v.zoom, d = dirOf(v.az, v.el);
      const eye = [v.t[0] + dist * d[0], v.t[1] + dist * d[1], v.t[2] + dist * d[2]];
      const f = [-d[0], -d[1], -d[2]], r = unit(cross(f, [0, 0, 1])), u = cross(r, f);
      return { eye, dist, d, f, r, u, M: lookAt(eye, v.t, [0, 0, 1]) };
    }
    const projection = () => perspective(fov, W / H, 0.01, 100);

    // camera auto-fit: the projected box fills most of the view
    let fitted = false;
    function fit() {
      fitted = true;
      for (let it = 0; it < 3; it++) {
        const { M } = camera(), P = projection();
        let e = 0;
        for (const i of [0, 1]) for (const j of [0, 1]) for (const k of [0, 1]) {
          const q = apply(P, apply(M, C(i, j, k)));
          e = Math.max(e, Math.abs(q[0] / q[3]), Math.abs(q[1] / q[3]));
        }
        if (!(e > 0)) return;
        view.zoom = Math.min(12, Math.max(ZMIN, view.zoom * 0.84 / e));
      }
      view0.zoom = view.zoom;
    }

    function draw() {
      const dpr = window.devicePixelRatio || 1;
      const full = document.fullscreenElement === wrap;
      const w = full ? window.innerWidth : scene.fill ? container.clientWidth || 800 : Math.min(container.clientWidth || 560, 640);
      const h = full ? window.innerHeight : scene.fill ? Math.max(300, Math.round(window.innerHeight - 24)) : Math.round(w * 0.82);
      if (w !== W || h !== H) {
        W = w; H = h;
        canvas.width = Math.round(w * dpr); canvas.height = Math.round(h * dpr);
        canvas.style.height = h + "px";
      }
      if (!fitted && scene.fit !== false) fit();
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.clearColor(0, 0, 0, 0);
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
      gl.enable(gl.DEPTH_TEST);
      const { eye, M } = camera(), P = projection();
      gl.useProgram(prog.p);
      gl.uniformMatrix4fv(prog.M, false, new Float32Array(M));
      gl.uniformMatrix4fv(prog.P, false, new Float32Array(P));
      const pixPerUnit = (canvas.height / 2) / Math.tan(fov / 2);
      const run = (d) => {
        gl.bindBuffer(gl.ARRAY_BUFFER, d.p);
        gl.vertexAttribPointer(prog.ap, 3, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(prog.ap);
        if (d.nn) { gl.bindBuffer(gl.ARRAY_BUFFER, d.nn); gl.vertexAttribPointer(prog.an, 3, gl.FLOAT, false, 0, 0); gl.enableVertexAttribArray(prog.an); }
        else { gl.disableVertexAttribArray(prog.an); gl.vertexAttrib3f(prog.an, 0, 0, 1); }
        gl.bindBuffer(gl.ARRAY_BUFFER, d.c);
        gl.vertexAttribPointer(prog.ac, 3, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(prog.ac);
        gl.uniform1f(prog.lit, d.lit);
        gl.uniform1f(prog.alpha, d.alpha);
        gl.uniform1f(prog.pt, d.mode === gl.POINTS ? d.pt || 1 : 0);
        gl.uniform1f(prog.flatN, d.flat || (d.lit && !d.nn) ? 1 : 0);
        if (d.world) {
          gl.uniform1f(prog.ps, d.world);
          gl.uniform1f(prog.psScale, pixPerUnit);
        } else {
          gl.uniform1f(prog.ps, (d.size || 1) * dpr);
          gl.uniform1f(prog.psScale, 0);
        }
        if (d.side === "front" && d.mode === gl.TRIANGLES) { gl.enable(gl.CULL_FACE); gl.cullFace(gl.BACK); }
        else if (d.side === "back" && d.mode === gl.TRIANGLES) { gl.enable(gl.CULL_FACE); gl.cullFace(gl.FRONT); }
        else gl.disable(gl.CULL_FACE);
        if (d.ib) {
          gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, d.ib);
          gl.drawElements(d.mode, d.n, d.itype, 0);
        } else gl.drawArrays(d.mode, 0, d.n);
        gl.disable(gl.CULL_FACE);
      };
      gl.disable(gl.BLEND);
      gl.depthMask(true);
      for (const d of draws) if (d.alpha >= 1) run(d);
      if (scene.frame !== false) {
        const c = ink(), col = [];
        for (let i = 0; i < framePos.length / 3; i++) col.push(...c);
        gl.bindBuffer(gl.ARRAY_BUFFER, frameCol);
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(col), gl.DYNAMIC_DRAW);
        gl.enable(gl.BLEND);
        gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
        run({ mode: gl.LINES, n: framePos.length / 3, p: frameBuf, nn: null, c: frameCol, lit: 0, alpha: 0.45 });
      }
      gl.enable(gl.BLEND);
      gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
      gl.depthMask(false);
      for (const d of draws) if (d.alpha < 1) run(d);
      // volumes last, over the rest (premultiplied colors)
      for (const v of vols) {
        gl.useProgram(v.vp.p);
        gl.uniformMatrix4fv(v.vp.M, false, new Float32Array(M));
        gl.uniformMatrix4fv(v.vp.P, false, new Float32Array(P));
        gl.uniform3fv(v.vp.eye, eye);
        gl.uniform3fv(v.vp.bmin, v.bmin);
        gl.uniform3fv(v.vp.bmax, v.bmax);
        gl.uniform1f(v.vp.samples, v.samples);
        gl.uniform1f(v.vp.alphaCoef, v.alphaCoef);
        gl.activeTexture(gl.TEXTURE0);
        gl.bindTexture(gl.TEXTURE_3D, v.tex);
        gl.uniform1i(v.vp.vol, 0);
        gl.activeTexture(gl.TEXTURE1);
        gl.bindTexture(gl.TEXTURE_2D, v.lut);
        gl.uniform1i(v.vp.lut, 1);
        gl.bindBuffer(gl.ARRAY_BUFFER, v.box);
        gl.vertexAttribPointer(v.vp.ap, 3, gl.FLOAT, false, 0, 0);
        gl.enableVertexAttribArray(v.vp.ap);
        gl.enable(gl.CULL_FACE);
        gl.cullFace(gl.FRONT); // the back faces: rays from the eye even inside the box
        gl.disable(gl.DEPTH_TEST);
        gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);
        gl.drawArrays(gl.TRIANGLES, 0, 36);
        gl.disable(gl.CULL_FACE);
        gl.enable(gl.DEPTH_TEST);
        gl.useProgram(prog.p);
      }
      gl.depthMask(true);
      placeLabels(M, P);
    }

    // screen position (CSS pixels) of a display point
    const screen = (M, P, p) => {
      const q = apply(P, apply(M, p));
      return [(q[0] / q[3] + 1) * W / 2, (1 - q[1] / q[3]) * H / 2, q[2] / q[3]];
    };

    function placeLabels(M, P) {
      let n = 0;
      const put = (x, y, text, style, z) => {
        if (!(z > -1 && z < 1)) return; // behind the eye (flying)
        const s = label(n++);
        s.style.left = x + "px"; s.style.top = y + "px"; s.style.display = "";
        s.textContent = text;
        s.style.fontStyle = style?.italic ? "italic" : "";
        s.style.fontSize = style?.size ? style.size + "px" : "";
        s.style.color = style?.color || "";
      };
      for (const t of geo.texts) { const p = screen(M, P, t.at); put(p[0], p[1], t.text, { size: t.size || 12, color: t.color }, p[2]); }
      if (scene.frame !== false) {
        const pts = {};
        for (const i of [0, 1]) for (const j of [0, 1]) for (const k of [0, 1]) pts[[i, j, k]] = screen(M, P, C(i, j, k));
        const all = Object.values(pts), cx = all.reduce((s, p) => s + p[0], 0) / 8, cy = all.reduce((s, p) => s + p[1], 0) / 8;
        for (let axis = 0; axis < 3; axis++) {
          let best = null, score = -Infinity;
          for (const [s, t, ax] of edges) {
            if (ax !== axis) continue;
            const a = pts[s], b = pts[t], m = [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
            const sc = (axis !== 2 ? m[1] - cy : cx - m[0]) - 40 * ((a[2] + b[2]) / 2);
            if (sc > score) { score = sc; best = [a, b]; }
          }
          const [a, b] = best, lo = scene.lo[axis], hi = scene.hi[axis];
          const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2, dl = Math.hypot(mx - cx, my - cy) || 1;
          const ox = (mx - cx) / dl, oy = (my - cy) / dl;
          const { ticks, step } = niceTicks(lo, hi, 4);
          for (const v of ticks) {
            if (v < lo - 1e-9 * (hi - lo) || v > hi + 1e-9 * (hi - lo)) continue;
            const f = hi > lo ? (v - lo) / (hi - lo) : 0.5;
            put(a[0] + (b[0] - a[0]) * f + 14 * ox, a[1] + (b[1] - a[1]) * f + 12 * oy, tickLabel(v, step), null, Math.max(a[2], b[2]));
          }
          const name = (scene.labels || [])[axis];
          if (name) put(mx + 34 * ox, my + 30 * oy, axisLabel(name), { italic: true, size: 12 }, Math.max(a[2], b[2]));
        }
      }
      for (let i = n; i < labels.length; i++) labels[i].style.display = "none";
    }

    // ---- navigation: orbit (default) and fly, with smooth motion.
    // Orbit: drag rotates about the target (with inertia), right- or
    // shift-drag pans, the wheel zooms toward the cursor, a double-click
    // glides to orbit the point under it.  Fly (F): mouse look (pointer
    // lock), W A S D / arrows, Space or E up, Q or C down, Shift faster,
    // wheel sets the speed; a gamepad flies too.  Keys work in both modes.
    let raf = 0, lastT = 0, fly = false, spin = null, auto = false, tween = null, speed = 1;
    let vel = [0, 0, 0];
    const keys = new Set();
    const clampEl = (e) => Math.max(-89, Math.min(89, e));
    const redraw = () => { if (!raf && canvas.isConnected) raf = requestAnimationFrame(tick); };
    // turn about the eye (fly) or about the target (orbit)
    function look(daz, del) {
      const { eye, dist } = camera();
      view.az += daz; view.el = clampEl(view.el + del);
      const d = dirOf(view.az, view.el);
      view.t = [eye[0] - dist * d[0], eye[1] - dist * d[1], eye[2] - dist * d[2]];
    }
    function orbit(daz, del) { view.az += daz; view.el = clampEl(view.el + del); }
    // the ray through the CSS pixel (x, y)
    function ray(x, y) {
      const c = camera(), th = Math.tan(fov / 2), px = (2 * x / W - 1) * th * (W / H), py = (1 - 2 * y / H) * th;
      return { o: c.eye, dir: unit([0, 1, 2].map((i) => c.f[i] + px * c.r[i] + py * c.u[i])), c };
    }
    // the nearest surface point on a ray (Moller-Trumbore), else the
    // middle of its run through a volume, else null
    function pick(x, y) {
      const { o, dir } = ray(x, y);
      let best = Infinity;
      const tri = (P, a, b, c) => {
        const e1x = P[b] - P[a], e1y = P[b + 1] - P[a + 1], e1z = P[b + 2] - P[a + 2];
        const e2x = P[c] - P[a], e2y = P[c + 1] - P[a + 1], e2z = P[c + 2] - P[a + 2];
        const px = dir[1] * e2z - dir[2] * e2y, py = dir[2] * e2x - dir[0] * e2z, pz = dir[0] * e2y - dir[1] * e2x;
        const det = e1x * px + e1y * py + e1z * pz;
        if (Math.abs(det) < 1e-12) return;
        const inv = 1 / det, sx = o[0] - P[a], sy = o[1] - P[a + 1], sz = o[2] - P[a + 2];
        const u = (sx * px + sy * py + sz * pz) * inv;
        if (u < 0 || u > 1) return;
        const qx = sy * e1z - sz * e1y, qy = sz * e1x - sx * e1z, qz = sx * e1y - sy * e1x;
        const v = (dir[0] * qx + dir[1] * qy + dir[2] * qz) * inv;
        if (v < 0 || u + v > 1) return;
        const t = (e2x * qx + e2y * qy + e2z * qz) * inv;
        if (t > 1e-4 && t < best) best = t;
      };
      for (const t of geo.tris) for (let i = 0; i + 8 < t.pos.length; i += 9) tri(t.pos, i, i + 3, i + 6);
      for (const m of geo.meshes) for (let i = 0; i + 2 < m.idx.length; i += 3) tri(m.pos, 3 * m.idx[i], 3 * m.idx[i + 1], 3 * m.idx[i + 2]);
      if (best === Infinity) {
        for (const v of geo.volumes) {
          let tn = 0, tf = Infinity;
          for (let i = 0; i < 3; i++) {
            const a = (v.bmin[i] - o[i]) / dir[i], b = (v.bmax[i] - o[i]) / dir[i];
            tn = Math.max(tn, Math.min(a, b)); tf = Math.min(tf, Math.max(a, b));
          }
          if (tf > tn) best = Math.min(best, (tn + tf) / 2);
        }
      }
      return best === Infinity ? null : [o[0] + best * dir[0], o[1] + best * dir[1], o[2] + best * dir[2]];
    }
    // glide to a view
    const ease = (x) => x * x * (3 - 2 * x);
    function glide(to, ms = 550) {
      const from = { ...view, t: [...view.t] };
      let daz = ((to.az - from.az) % 360 + 540) % 360 - 180;
      tween = { from, to: { ...to, az: from.az + daz }, t0: performance.now(), ms };
      vel = [0, 0, 0]; spin = null;
      redraw();
    }
    // orbit about p from where the eye is, moving in a little
    function focus(p) {
      const { eye } = camera(), d = sub(eye, p), L = Math.hypot(...d) || 1;
      const el = (Math.asin(Math.max(-1, Math.min(1, d[2] / L))) * 180) / Math.PI;
      const az = (Math.atan2(d[1], d[0]) * 180) / Math.PI;
      glide({ az, el: clampEl(el), zoom: Math.min(ZMAX, Math.max(ZMIN, 5.2 / (L * 0.7))), t: p });
    }
    function home() { glide(view0); }

    function tick(now) {
      raf = 0;
      const dt = lastT ? Math.min(0.1, (now - lastT) / 1000) : 0;
      lastT = now;
      let busy = false;
      if (tween) {
        const x = Math.min(1, (now - tween.t0) / tween.ms), k = ease(x), a = tween.from, b = tween.to;
        view.az = a.az + (b.az - a.az) * k; view.el = a.el + (b.el - a.el) * k;
        view.zoom = Math.exp(Math.log(a.zoom) + (Math.log(b.zoom) - Math.log(a.zoom)) * k);
        view.t = [0, 1, 2].map((i) => a.t[i] + (b.t[i] - a.t[i]) * k);
        if (x >= 1) tween = null; else busy = true;
      }
      // movement input: right, up, forward
      const inp = [0, 0, 0];
      const k = (c) => keys.has(c) ? 1 : 0;
      inp[0] = k("KeyD") - k("KeyA");
      inp[1] = k("KeyE") + k("Space") - k("KeyQ") - k("KeyC");
      inp[2] = k("KeyW") - k("KeyS");
      let lookX = k("ArrowLeft") - k("ArrowRight"), lookY = k("ArrowUp") - k("ArrowDown");
      const gp = fly && navigator.getGamepads ? [...navigator.getGamepads()].find((g) => g && g.connected) : null;
      if (gp) {
        const ax = (i) => (Math.abs(gp.axes[i] || 0) > 0.15 ? gp.axes[i] : 0), bt = (i) => gp.buttons[i]?.value || 0;
        inp[0] += ax(0); inp[2] -= ax(1); inp[1] += bt(7) - bt(6);
        lookX -= ax(2) * 1.5; lookY -= ax(3) * 1.5;
        if (bt(0) > 0.5 || bt(10) > 0.5) inp.forEach((v, i) => (inp[i] = v * 3));
        busy = true; // keep polling while flying with a gamepad
      }
      if (lookX || lookY) {
        (fly ? look : orbit)(lookX * 100 * dt, lookY * 70 * dt);
        busy = true;
      }
      const fast = keys.has("ShiftLeft") || keys.has("ShiftRight") ? 4 : 1;
      const c = camera(), v = speed * fast * (fly ? 1 : c.dist / 5.2 * 1.5);
      const want = [0, 1, 2].map((i) => (inp[0] * c.r[i] + inp[2] * c.f[i]) * v + (i === 2 ? inp[1] * v : 0));
      const s = 1 - Math.exp(-dt * 9);
      vel = vel.map((x, i) => x + (want[i] - x) * s);
      if (Math.hypot(...vel) > 1e-4 || inp.some((x) => x)) {
        view.t = view.t.map((x, i) => Math.max(-30, Math.min(30, x + vel[i] * dt)));
        busy = true;
      } else vel = [0, 0, 0];
      if (spin) {
        orbit(spin[0] * dt, spin[1] * dt);
        const damp = Math.exp(-dt * 2.5);
        spin = [spin[0] * damp, spin[1] * damp];
        if (Math.hypot(...spin) < 3) spin = null; else busy = true;
      }
      if (auto) { orbit(-14 * dt, 0); busy = true; }
      draw();
      updateHud();
      if (busy) redraw(); else lastT = 0;
    }

    // ---- controls overlay: a small toolbar (shown on hover), the fly HUD and help
    const btnCss = "pointer-events:auto;font:11px system-ui,sans-serif;padding:2px 7px;border-radius:4px;" +
      "border:1px solid rgba(128,128,128,.5);background:rgba(255,255,255,.82);color:#222;cursor:pointer";
    const bar = document.createElement("div");
    bar.style.cssText = "position:absolute;left:6px;bottom:6px;display:flex;gap:4px;opacity:0;transition:opacity .2s;pointer-events:none";
    const mk = (text, title, fn) => {
      const b = document.createElement("button");
      b.type = "button"; b.textContent = text; b.title = title; b.style.cssText = btnCss;
      b.addEventListener("click", (e) => { e.stopPropagation(); fn(); canvas.focus(); });
      b.addEventListener("dblclick", (e) => e.stopPropagation());
      b.addEventListener("pointerdown", (e) => e.stopPropagation());
      bar.appendChild(b);
      return b;
    };
    mk("Home", "Back to the starting view (0)", home);
    const flyB = mk("Fly", "Fly through the scene like a game (F)", () => setFly(!fly));
    const spinB = mk("Spin", "Turntable rotation (T)", () => { auto = !auto; spinB.style.fontWeight = auto ? "700" : ""; redraw(); });
    if (wrap.requestFullscreen) mk("Full screen", "Full screen (Esc leaves)", () => {
      if (document.fullscreenElement) document.exitFullscreen(); else wrap.requestFullscreen().catch(() => {});
    });
    const help = document.createElement("div");
    help.style.cssText = "position:absolute;left:6px;bottom:34px;max-width:300px;padding:6px 9px;border-radius:6px;display:none;" +
      "background:rgba(20,20,24,.86);color:#eee;font:11px/1.45 system-ui,sans-serif;pointer-events:none";
    help.innerHTML = "<b>Orbit<\/b> drag: rotate (flick to spin) · right/shift-drag: pan · wheel: zoom to the cursor " +
      "(click the view first) · double-click: orbit that point · two fingers: pan and pinch<br>" +
      "<b>Move<\/b> W A S D, Space/E up, Q/C down, Shift faster, arrows turn<br>" +
      "<b>Fly<\/b> (F) click to look with the mouse (Esc releases) · wheel: speed · gamepad: sticks, triggers<br>" +
      "<b>Keys<\/b> 0 home · T turntable · +/- zoom";
    mk("?", "Controls", () => { help.style.display = help.style.display === "none" ? "" : "none"; });
    const hud = document.createElement("div");
    hud.style.cssText = "position:absolute;left:0;right:0;top:6px;text-align:center;display:none;pointer-events:none;" +
      "font:11px system-ui,sans-serif;color:#fff;text-shadow:0 0 3px #000,0 0 2px #000";
    const cross_ = document.createElement("div");
    cross_.style.cssText = "position:absolute;left:50%;top:50%;width:14px;height:14px;margin:-7px 0 0 -7px;display:none;pointer-events:none;" +
      "background:linear-gradient(#fff,#fff) center/2px 100% no-repeat,linear-gradient(#fff,#fff) center/100% 2px no-repeat;" +
      "mix-blend-mode:difference;opacity:.8";
    wrap.append(bar, help, hud, cross_);
    const hoverNone = typeof matchMedia !== "undefined" && matchMedia("(hover: none)").matches;
    const showBar = (on) => { bar.style.opacity = on || fly || hoverNone ? (hoverNone && !on ? "0.6" : "1") : "0"; };
    showBar(false);
    wrap.addEventListener("pointerenter", () => showBar(true));
    wrap.addEventListener("pointerleave", () => showBar(false));
    canvas.addEventListener("focus", () => showBar(true));
    canvas.addEventListener("blur", () => { keys.clear(); showBar(false); });
    let hudText = "";
    function updateHud() {
      if (!fly) return;
      const locked = document.pointerLockElement === canvas;
      const t = (locked ? "Esc releases the mouse" : "Click to look with the mouse") +
        " · WASD move · Space/Q up/down · Shift faster · wheel: speed ×" + speed.toFixed(speed < 1 ? 2 : 1) + " · F: orbit";
      if (t !== hudText) { hudText = t; hud.textContent = t; }
    }
    function setFly(on) {
      fly = on;
      flyB.style.fontWeight = fly ? "700" : "";
      hud.style.display = cross_.style.display = fly ? "" : "none";
      canvas.style.cursor = fly ? "crosshair" : "grab";
      if (!fly && document.pointerLockElement === canvas) document.exitPointerLock();
      spin = null; auto = false; spinB.style.fontWeight = "";
      showBar(true); hudText = ""; updateHud(); redraw();
    }
    document.addEventListener("pointerlockchange", () => { hudText = ""; if (fly) updateHud(); });

    // ---- pointers: one rotates (or looks), two pan and pinch; right/shift pans
    const ptrs = new Map();
    let two = null, drag = null;
    const pan = (dx, dy) => {
      const c = camera(), s = (2 * c.dist * Math.tan(fov / 2)) / H;
      view.t = view.t.map((x, i) => x - (dx * c.r[i] - dy * c.u[i]) * s);
    };
    const pair = () => {
      const [p, q] = [...ptrs.values()];
      return { d: Math.hypot(p[0] - q[0], p[1] - q[1]), m: [(p[0] + q[0]) / 2, (p[1] + q[1]) / 2] };
    };
    canvas.addEventListener("contextmenu", (e) => e.preventDefault());
    canvas.addEventListener("pointerdown", (e) => {
      canvas.focus({ preventScroll: true });
      tween = null; spin = null;
      if (fly && e.pointerType === "mouse" && document.pointerLockElement !== canvas && canvas.requestPointerLock) {
        try { const r = canvas.requestPointerLock(); if (r && r.catch) r.catch(() => {}); } catch (err) { /* not allowed here */ }
      }
      if (document.pointerLockElement === canvas) return;
      canvas.setPointerCapture(e.pointerId);
      ptrs.set(e.pointerId, [e.clientX, e.clientY]);
      if (!fly) canvas.style.cursor = "grabbing";
      drag = { pan: e.button === 2 || e.button === 1 || e.shiftKey, v: [0, 0], at: performance.now() };
      if (ptrs.size === 2) two = pair();
    });
    canvas.addEventListener("pointermove", (e) => {
      if (document.pointerLockElement === canvas) {
        look(-e.movementX * 0.14, -e.movementY * 0.14);
        redraw();
        return;
      }
      const last = ptrs.get(e.pointerId);
      if (!last) return;
      const now = [e.clientX, e.clientY], dx = now[0] - last[0], dy = now[1] - last[1];
      ptrs.set(e.pointerId, now);
      if (ptrs.size === 2 && two) {
        const q = pair(), r = q.d / (two.d || 1);
        pan(q.m[0] - two.m[0], q.m[1] - two.m[1]);
        if (fly) { const c = camera(); view.t = view.t.map((x, i) => x + c.f[i] * Math.log(r) * 2 * speed); }
        else view.zoom = Math.min(ZMAX, Math.max(ZMIN, view.zoom * r));
        two = q;
      } else if (ptrs.size === 1 && drag) {
        if (drag.pan && !fly) pan(dx, dy);
        else if (fly) look(dx * 0.25, dy * 0.25);
        else {
          orbit(-dx * 0.5, dy * 0.5);
          const t = performance.now(), ms = Math.max(1, t - drag.at);
          drag.v = [0.7 * drag.v[0] + 0.3 * (-dx * 0.5 * 1000 / ms), 0.7 * drag.v[1] + 0.3 * (dy * 0.5 * 1000 / ms)];
          drag.at = t;
        }
      }
      redraw();
    });
    const up = (e) => {
      if (!ptrs.has(e.pointerId)) return;
      ptrs.delete(e.pointerId);
      if (ptrs.size < 2) two = null;
      if (!ptrs.size) {
        if (drag && !drag.pan && !fly && performance.now() - drag.at < 60 && Math.hypot(...drag.v) > 40) { spin = drag.v; redraw(); }
        drag = null;
        canvas.style.cursor = fly ? "crosshair" : "grab";
      }
    };
    canvas.addEventListener("pointerup", up);
    canvas.addEventListener("pointercancel", up);
    canvas.addEventListener("wheel", (e) => {
      if (document.activeElement !== canvas && !e.ctrlKey && !scene.fill && document.fullscreenElement !== wrap) return; // let the page scroll
      e.preventDefault();
      if (fly) { speed = Math.min(20, Math.max(0.05, speed * Math.exp(-e.deltaY * 0.002))); updateHud(); return; }
      // zoom about the point under the cursor (on the plane through the target)
      const b = canvas.getBoundingClientRect(), { o, dir, c } = ray(e.clientX - b.left, e.clientY - b.top);
      const q = o.map((x, i) => x + dir[i] * (c.dist / Math.max(1e-6, dot(dir, c.f))));
      const z = Math.min(ZMAX, Math.max(ZMIN, view.zoom * Math.exp(-e.deltaY * 0.0015))), s = view.zoom / z;
      view.t = view.t.map((x, i) => q[i] + (x - q[i]) * s);
      view.zoom = z;
      tween = null;
      redraw();
    }, { passive: false });
    canvas.addEventListener("dblclick", (e) => {
      if (fly) return;
      const b = canvas.getBoundingClientRect(), p = pick(e.clientX - b.left, e.clientY - b.top);
      if (p) focus(p); else home();
    });
    canvas.addEventListener("keydown", (e) => {
      if (e.ctrlKey || e.metaKey || e.altKey) return;
      const c = e.code;
      if (c === "KeyF") setFly(!fly);
      else if (c === "KeyT") { auto = !auto; spinB.style.fontWeight = auto ? "700" : ""; }
      else if (c === "Digit0" || c === "Numpad0" || c === "Home") home();
      else if (e.key === "+" || e.key === "=") view.zoom = Math.min(ZMAX, view.zoom * 1.15);
      else if (e.key === "-") view.zoom = Math.max(ZMIN, view.zoom / 1.15);
      else if (c === "Escape" && fly && document.pointerLockElement !== canvas) setFly(false);
      else if (/^(Key[WASDEQC]|Space|Arrow(Left|Right|Up|Down)|Shift(Left|Right))$/.test(c)) { keys.add(c); tween = null; }
      else return;
      e.preventDefault();
      redraw();
    });
    canvas.addEventListener("keyup", (e) => { keys.delete(e.code); });
    window.addEventListener("gamepadconnected", () => { if (fly) redraw(); });
    // for tests and embedding pages: the camera state and the modes
    canvas.sagebrush = { get view() { return { ...view, t: [...view.t] }; }, get fly() { return fly; }, setFly, home, focus, pick };
    if (typeof ResizeObserver !== "undefined") new ResizeObserver(redraw).observe(container);
    if (scene.fill) window.addEventListener("resize", redraw);
    document.addEventListener("fullscreenchange", redraw);
    if (typeof matchMedia !== "undefined") matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change", redraw);
    new MutationObserver(redraw).observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme", "class"] });
    draw();
    return true;
  }

  function compile(gl, vs, fs) {
    const sh = (type, src) => {
      const s = gl.createShader(type);
      gl.shaderSource(s, src);
      gl.compileShader(s);
      if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) { console.warn("viewer3d shader:", gl.getShaderInfoLog(s)); return null; }
      return s;
    };
    const v = sh(gl.VERTEX_SHADER, vs), f = sh(gl.FRAGMENT_SHADER, fs);
    if (!v || !f) return null;
    const p = gl.createProgram();
    gl.attachShader(p, v); gl.attachShader(p, f); gl.linkProgram(p);
    return gl.getProgramParameter(p, gl.LINK_STATUS) ? p : null;
  }

  function program(gl, gl2, deriv) {
    // GLSL ES 3.00 under WebGL2 (dFdx built in), else 1.00
    const vs = gl2 ? "#version 300 es\n#define attribute in\n#define varying out\n" + VS : VS;
    const fs = gl2
      ? "#version 300 es\nprecision highp float;\n#define FLATOK 1\n#define varying in\nout vec4 fragColor_;\n#define gl_FragColor fragColor_\n" + FS
      : (deriv ? "#extension GL_OES_standard_derivatives : enable\n#define FLATOK 1\n" : "#define FLATOK 0\n") + "precision highp float;\n" + FS;
    const p = compile(gl, vs, fs);
    if (!p) return null;
    const u = (n) => gl.getUniformLocation(p, n);
    return { p, ap: gl.getAttribLocation(p, "p"), an: gl.getAttribLocation(p, "n"), ac: gl.getAttribLocation(p, "c"),
      M: u("M"), P: u("P"), ps: u("ps"), psScale: u("psScale"), lit: u("lit"), alpha: u("alpha"), pt: u("pt"), flatN: u("flatN") };
  }

  function volumeProgram(gl) {
    const p = compile(gl, VOL_VS, VOL_FS);
    if (!p) return null;
    const u = (n) => gl.getUniformLocation(p, n);
    return { p, ap: gl.getAttribLocation(p, "p"), M: u("M"), P: u("P"), eye: u("eye"), bmin: u("bmin"), bmax: u("bmax"),
      samples: u("samples"), alphaCoef: u("alphaCoef"), vol: u("vol"), lut: u("lut") };
  }

  window.SagebrushViewer3d = { mount };
})();
